<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>fdl</string>
    <string>kalos</string>
   </array>
  <key>name</key>
  <string>kalos</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.kalos</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b(?:if|else|for|in|loop|var|const|import|handle|on|break|continue|debugger)(?![a-z0-9_]))</string>
          <key>name</key>
          <string>keyword.kalos</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.kalos</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.kalos</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(;)</string>
          <key>name</key>
          <string>punctuation.kalos</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#expression</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(#.*)</string>
          <key>name</key>
          <string>comment.kalos</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.kalos</string>
        </dict>
       </array>
    </dict>
    <key>expression</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.kalos</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#expression__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.kalos</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>([\x{003d}\x{007c}\x{0026}\-\x{002b}\x{002a}\x{002f}\.\x{003c}\x{003e}]|&lt;&lt;|&gt;&gt;|==|!=|&lt;=|&gt;=)</string>
          <key>name</key>
          <string>punctuation.kalos</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b[a-zA-Z_][a-zA-Z0-9_]*)</string>
          <key>name</key>
          <string>variable.kalos</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.kalos</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#expression__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.kalos</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>expression__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#expression</string>
        </dict>
       </array>
    </dict>
    <key>expression__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>({{)</string>
          <key>name</key>
          <string>string.kalos</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(}})</string>
          <key>name</key>
          <string>string.kalos</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>({)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.kalos</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#expression__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.kalos</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\\(?:[\x{005c}\x{0022}nrt]))</string>
          <key>name</key>
          <string>string.kalos</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\x{0022}\x{005c}])</string>
          <key>name</key>
          <string>string.kalos</string>
        </dict>
       </array>
    </dict>
    <key>expression__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#expression</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.kalos</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
