/* Generated by re2c 2.1.1 on Fri Jun 25 14:29:59 2021 */
#include "_kalos_defines.h"
#include "_kalos_lex.h"

enum yyc_state {
    yycinit,
    yycinstring,
    yycinstringmulti,
    yyccomment,
    yycstringformat,
};

#define KALOS_TOKEN(x) #x ,
const char* kalos_token_strings[] = {
    #include "_kalos_constants.inc"
    "<invalid>",
};

enum string_state {
    STRING_STATE_NORMAL,
    STRING_STATE_EXPR,
    STRING_STATE_DONE,
};

#define KALOS_COPY_TOKEN kalos_lex_strncpy(output, word_start, word_end - word_start)

void kalos_lex_init(const char kalos_far* s, kalos_lex_state* state) {
    state->s = s;
    state->line = 1;
    state->string_interp_state = STRING_STATE_NORMAL;
    state->string_interp_mode = yycinit;
}

kalos_token kalos_lex_peek(kalos_lex_state* state, char* output) {
    kalos_lex_state temp = *state;
    return kalos_lex(&temp, output);
}

kalos_token kalos_lex(kalos_lex_state* state, char* output) {
    enum yyc_state c = yycinit;
    if (state->string_interp_state == STRING_STATE_DONE) {
        c = state->string_interp_mode;
        state->string_interp_state = STRING_STATE_NORMAL;
    }
    const char kalos_far** s = &state->s;
    int* line = &state->line;
    *output = 0;

    const char kalos_far* word_start;
    const char kalos_far* word_end;
    const char kalos_far* ch;
    const char kalos_far* YYMARKER;

    const char kalos_far *yyt1; 
    for (;;) {
    
{
	char yych;
	unsigned int yyaccept = 0;
	switch (c) {
	case yycinit:
		goto yyc_init;
	case yycinstring:
		goto yyc_instring;
	case yycinstringmulti:
		goto yyc_instringmulti;
	case yycstringformat:
		goto yyc_stringformat;
	case yyccomment:
		goto yyc_comment;
	}
/* *********************************** */
yyc_init:
	yych = *(*s);
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case '\r':
	case ' ':	goto yy6;
	case '\n':	goto yy9;
	case '!':	goto yy11;
	case '"':	goto yy13;
	case '#':	goto yy15;
	case '%':	goto yy17;
	case '&':	goto yy19;
	case '(':	goto yy21;
	case ')':	goto yy23;
	case '*':	goto yy25;
	case '+':	goto yy27;
	case ',':	goto yy29;
	case '-':	goto yy31;
	case '.':	goto yy33;
	case '/':	goto yy35;
	case '0':
		yyt1 = (*s);
		goto yy37;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt1 = (*s);
		goto yy39;
	case ':':	goto yy41;
	case ';':	goto yy43;
	case '<':	goto yy45;
	case '=':	goto yy47;
	case '>':	goto yy49;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'g':
	case 'j':
	case 'k':
	case 'q':
	case 'u':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = (*s);
		goto yy51;
	case '[':	goto yy54;
	case ']':	goto yy56;
	case '^':	goto yy58;
	case 'a':
		yyt1 = (*s);
		goto yy60;
	case 'b':
		yyt1 = (*s);
		goto yy61;
	case 'c':
		yyt1 = (*s);
		goto yy62;
	case 'd':
		yyt1 = (*s);
		goto yy64;
	case 'e':
		yyt1 = (*s);
		goto yy65;
	case 'f':
		yyt1 = (*s);
		goto yy66;
	case 'h':
		yyt1 = (*s);
		goto yy67;
	case 'i':
		yyt1 = (*s);
		goto yy68;
	case 'l':
		yyt1 = (*s);
		goto yy69;
	case 'm':
		yyt1 = (*s);
		goto yy70;
	case 'n':
		yyt1 = (*s);
		goto yy71;
	case 'o':
		yyt1 = (*s);
		goto yy72;
	case 'p':
		yyt1 = (*s);
		goto yy73;
	case 'r':
		yyt1 = (*s);
		goto yy74;
	case 's':
		yyt1 = (*s);
		goto yy75;
	case 't':
		yyt1 = (*s);
		goto yy76;
	case 'v':
		yyt1 = (*s);
		goto yy77;
	case 'w':
		yyt1 = (*s);
		goto yy78;
	case '{':	goto yy79;
	case '|':	goto yy81;
	case '}':	goto yy83;
	case '~':	goto yy85;
	default:	goto yy4;
	}
yy2:
	++(*s);
	{ return KALOS_TOKEN_EOF; }
yy4:
	++(*s);
	{ return KALOS_TOKEN_ERROR; }
yy6:
	yych = *++(*s);
	switch (yych) {
	case '\t':
	case '\r':
	case ' ':	goto yy6;
	default:	goto yy8;
	}
yy8:
	{ continue; }
yy9:
	++(*s);
	{ if (state->string_interp_state != STRING_STATE_NORMAL) return KALOS_TOKEN_ERROR; (*line)++; continue; }
yy11:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy87;
	default:	goto yy12;
	}
yy12:
	{ return KALOS_TOKEN_BANG; }
yy13:
	yyaccept = 0;
	yych = *(YYMARKER = ++(*s));
	switch (yych) {
	case '"':	goto yy89;
	default:	goto yy14;
	}
yy14:
	c = yycinstring;
	goto yyc_instring;
yy15:
	++(*s);
	c = yyccomment;
	goto yyc_comment;
yy17:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy91;
	default:	goto yy18;
	}
yy18:
	{ return KALOS_TOKEN_PERCENT; }
yy19:
	yych = *++(*s);
	switch (yych) {
	case '&':	goto yy93;
	case '=':	goto yy95;
	default:	goto yy20;
	}
yy20:
	{ return KALOS_TOKEN_BITAND; }
yy21:
	++(*s);
	{ return KALOS_TOKEN_PAREN_OPEN; }
yy23:
	++(*s);
	{ return KALOS_TOKEN_PAREN_CLOSE; }
yy25:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy97;
	default:	goto yy26;
	}
yy26:
	{ return KALOS_TOKEN_STAR; }
yy27:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy99;
	default:	goto yy28;
	}
yy28:
	{ return KALOS_TOKEN_PLUS; }
yy29:
	++(*s);
	{ return KALOS_TOKEN_COMMA; }
yy31:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy101;
	default:	goto yy32;
	}
yy32:
	{ return KALOS_TOKEN_MINUS; }
yy33:
	yyaccept = 1;
	yych = *(YYMARKER = ++(*s));
	switch (yych) {
	case '.':	goto yy103;
	default:	goto yy34;
	}
yy34:
	{ return KALOS_TOKEN_PERIOD; }
yy35:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy104;
	default:	goto yy36;
	}
yy36:
	{ return KALOS_TOKEN_SLASH; }
yy37:
	yyaccept = 2;
	yych = *(YYMARKER = ++(*s));
	switch (yych) {
	case 'X':
	case 'x':	goto yy106;
	default:	goto yy38;
	}
yy38:
	word_start = yyt1;
	word_end = (*s);
	{ KALOS_COPY_TOKEN; output[word_end - word_start] = 0; return KALOS_TOKEN_INTEGER; }
yy39:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy39;
	default:	goto yy38;
	}
yy41:
	++(*s);
	{
            if (state->string_interp_state == STRING_STATE_EXPR) {
                c = yycstringformat;
                continue;
            }
            return KALOS_TOKEN_COLON;
        }
yy43:
	++(*s);
	{ return KALOS_TOKEN_SEMI; }
yy45:
	yych = *++(*s);
	switch (yych) {
	case '<':	goto yy107;
	case '=':	goto yy109;
	default:	goto yy46;
	}
yy46:
	{ return KALOS_TOKEN_LT; }
yy47:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy111;
	default:	goto yy48;
	}
yy48:
	{ return KALOS_TOKEN_EQ; }
yy49:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy113;
	case '>':	goto yy115;
	default:	goto yy50;
	}
yy50:
	{ return KALOS_TOKEN_GT; }
yy51:
	yych = *++(*s);
yy52:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy53;
	}
yy53:
	word_start = yyt1;
	word_end = (*s);
	{ KALOS_COPY_TOKEN; output[word_end - word_start] = 0; return KALOS_TOKEN_WORD; }
yy54:
	++(*s);
	{ return KALOS_TOKEN_SQBRA_OPEN; }
yy56:
	++(*s);
	{ return KALOS_TOKEN_SQBRA_CLOSE; }
yy58:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy117;
	default:	goto yy59;
	}
yy59:
	{ return KALOS_TOKEN_BITXOR; }
yy60:
	yych = *++(*s);
	switch (yych) {
	case 'n':	goto yy119;
	default:	goto yy52;
	}
yy61:
	yych = *++(*s);
	switch (yych) {
	case 'o':	goto yy120;
	case 'r':	goto yy121;
	default:	goto yy52;
	}
yy62:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	case 'o':	goto yy122;
	default:	goto yy63;
	}
yy63:
	{ return KALOS_TOKEN_C; }
yy64:
	yych = *++(*s);
	switch (yych) {
	case 'e':	goto yy123;
	case 'i':	goto yy124;
	default:	goto yy52;
	}
yy65:
	yych = *++(*s);
	switch (yych) {
	case 'l':	goto yy125;
	default:	goto yy52;
	}
yy66:
	yych = *++(*s);
	switch (yych) {
	case 'a':	goto yy126;
	case 'n':	goto yy127;
	case 'o':	goto yy129;
	default:	goto yy52;
	}
yy67:
	yych = *++(*s);
	switch (yych) {
	case 'a':	goto yy130;
	default:	goto yy52;
	}
yy68:
	yych = *++(*s);
	switch (yych) {
	case 'd':	goto yy131;
	case 'f':	goto yy132;
	case 'm':	goto yy134;
	case 'n':	goto yy135;
	default:	goto yy52;
	}
yy69:
	yych = *++(*s);
	switch (yych) {
	case 'o':	goto yy137;
	default:	goto yy52;
	}
yy70:
	yych = *++(*s);
	switch (yych) {
	case 'o':	goto yy138;
	default:	goto yy52;
	}
yy71:
	yych = *++(*s);
	switch (yych) {
	case 'a':	goto yy139;
	case 'u':	goto yy140;
	default:	goto yy52;
	}
yy72:
	yych = *++(*s);
	switch (yych) {
	case 'b':	goto yy141;
	case 'n':	goto yy142;
	default:	goto yy52;
	}
yy73:
	yych = *++(*s);
	switch (yych) {
	case 'r':	goto yy144;
	default:	goto yy52;
	}
yy74:
	yych = *++(*s);
	switch (yych) {
	case 'e':	goto yy145;
	default:	goto yy52;
	}
yy75:
	yych = *++(*s);
	switch (yych) {
	case 't':	goto yy146;
	default:	goto yy52;
	}
yy76:
	yych = *++(*s);
	switch (yych) {
	case 'r':	goto yy147;
	default:	goto yy52;
	}
yy77:
	yych = *++(*s);
	switch (yych) {
	case 'a':	goto yy148;
	case 'o':	goto yy149;
	default:	goto yy52;
	}
yy78:
	yych = *++(*s);
	switch (yych) {
	case 'r':	goto yy150;
	default:	goto yy52;
	}
yy79:
	++(*s);
	{ return KALOS_TOKEN_BRA_OPEN; }
yy81:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy151;
	case '|':	goto yy153;
	default:	goto yy82;
	}
yy82:
	{ return KALOS_TOKEN_BITOR; }
yy83:
	++(*s);
	{
            if (state->string_interp_state == STRING_STATE_EXPR) { 
                state->string_interp_state = STRING_STATE_DONE;
                output[0] = 0; // empty format spec
                return KALOS_TOKEN_STRING_FORMAT_SPEC;
            }
            return KALOS_TOKEN_BRA_CLOSE; 
        }
yy85:
	++(*s);
	{ return KALOS_TOKEN_TILDE; }
yy87:
	++(*s);
	{ return KALOS_TOKEN_NOTEQ; }
yy89:
	yych = *++(*s);
	switch (yych) {
	case '"':	goto yy155;
	default:	goto yy90;
	}
yy90:
	(*s) = YYMARKER;
	switch (yyaccept) {
	case 0:
		goto yy14;
	case 1:
		goto yy34;
	default:
		goto yy38;
	}
yy91:
	++(*s);
	{ return KALOS_TOKEN_EQ_PERCENT; }
yy93:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy157;
	default:	goto yy94;
	}
yy94:
	{ return KALOS_TOKEN_LOGAND; }
yy95:
	++(*s);
	{ return KALOS_TOKEN_EQ_BITAND; }
yy97:
	++(*s);
	{ return KALOS_TOKEN_EQ_STAR; }
yy99:
	++(*s);
	{ return KALOS_TOKEN_EQ_PLUS; }
yy101:
	++(*s);
	{ return KALOS_TOKEN_EQ_MINUS; }
yy103:
	yych = *++(*s);
	switch (yych) {
	case '.':	goto yy159;
	default:	goto yy90;
	}
yy104:
	++(*s);
	{ return KALOS_TOKEN_EQ_SLASH; }
yy106:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy161;
	default:	goto yy90;
	}
yy107:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy163;
	default:	goto yy108;
	}
yy108:
	{ return KALOS_TOKEN_LEFT_SHIFT; }
yy109:
	++(*s);
	{ return KALOS_TOKEN_LTE; }
yy111:
	++(*s);
	{ return KALOS_TOKEN_EQEQ; }
yy113:
	++(*s);
	{ return KALOS_TOKEN_GTE; }
yy115:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy165;
	default:	goto yy116;
	}
yy116:
	{ return KALOS_TOKEN_RIGHT_SHIFT; }
yy117:
	++(*s);
	{ return KALOS_TOKEN_EQ_BITXOR; }
yy119:
	yych = *++(*s);
	switch (yych) {
	case 'y':	goto yy167;
	default:	goto yy52;
	}
yy120:
	yych = *++(*s);
	switch (yych) {
	case 'o':	goto yy169;
	default:	goto yy52;
	}
yy121:
	yych = *++(*s);
	switch (yych) {
	case 'e':	goto yy170;
	default:	goto yy52;
	}
yy122:
	yych = *++(*s);
	switch (yych) {
	case 'n':	goto yy171;
	default:	goto yy52;
	}
yy123:
	yych = *++(*s);
	switch (yych) {
	case 'b':	goto yy172;
	default:	goto yy52;
	}
yy124:
	yych = *++(*s);
	switch (yych) {
	case 's':	goto yy173;
	default:	goto yy52;
	}
yy125:
	yych = *++(*s);
	switch (yych) {
	case 's':	goto yy174;
	default:	goto yy52;
	}
yy126:
	yych = *++(*s);
	switch (yych) {
	case 'l':	goto yy175;
	default:	goto yy52;
	}
yy127:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy128;
	}
yy128:
	{ return KALOS_TOKEN_FN; }
yy129:
	yych = *++(*s);
	switch (yych) {
	case 'r':	goto yy176;
	default:	goto yy52;
	}
yy130:
	yych = *++(*s);
	switch (yych) {
	case 'n':	goto yy178;
	default:	goto yy52;
	}
yy131:
	yych = *++(*s);
	switch (yych) {
	case 'l':	goto yy179;
	default:	goto yy52;
	}
yy132:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy133;
	}
yy133:
	{ return KALOS_TOKEN_IF; }
yy134:
	yych = *++(*s);
	switch (yych) {
	case 'p':	goto yy181;
	default:	goto yy52;
	}
yy135:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	case 't':	goto yy182;
	default:	goto yy136;
	}
yy136:
	{ return KALOS_TOKEN_IN; }
yy137:
	yych = *++(*s);
	switch (yych) {
	case 'o':	goto yy183;
	default:	goto yy52;
	}
yy138:
	yych = *++(*s);
	switch (yych) {
	case 'd':	goto yy184;
	default:	goto yy52;
	}
yy139:
	yych = *++(*s);
	switch (yych) {
	case 'm':	goto yy185;
	default:	goto yy52;
	}
yy140:
	yych = *++(*s);
	switch (yych) {
	case 'm':	goto yy186;
	default:	goto yy52;
	}
yy141:
	yych = *++(*s);
	switch (yych) {
	case 'j':	goto yy187;
	default:	goto yy52;
	}
yy142:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy143;
	}
yy143:
	{ return KALOS_TOKEN_ON; }
yy144:
	yych = *++(*s);
	switch (yych) {
	case 'e':	goto yy188;
	case 'o':	goto yy189;
	default:	goto yy52;
	}
yy145:
	yych = *++(*s);
	switch (yych) {
	case 'a':	goto yy190;
	case 't':	goto yy191;
	default:	goto yy52;
	}
yy146:
	yych = *++(*s);
	switch (yych) {
	case 'r':	goto yy192;
	default:	goto yy52;
	}
yy147:
	yych = *++(*s);
	switch (yych) {
	case 'u':	goto yy193;
	default:	goto yy52;
	}
yy148:
	yych = *++(*s);
	switch (yych) {
	case 'r':	goto yy194;
	default:	goto yy52;
	}
yy149:
	yych = *++(*s);
	switch (yych) {
	case 'i':	goto yy196;
	default:	goto yy52;
	}
yy150:
	yych = *++(*s);
	switch (yych) {
	case 'i':	goto yy197;
	default:	goto yy52;
	}
yy151:
	++(*s);
	{ return KALOS_TOKEN_EQ_BITOR; }
yy153:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy198;
	default:	goto yy154;
	}
yy154:
	{ return KALOS_TOKEN_LOGOR; }
yy155:
	++(*s);
	c = yycinstringmulti;
	goto yyc_instringmulti;
yy157:
	++(*s);
	{ return KALOS_TOKEN_EQ_LOGAND; }
yy159:
	++(*s);
	{ return KALOS_TOKEN_ELLIPSIS; }
yy161:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy161;
	default:	goto yy38;
	}
yy163:
	++(*s);
	{ return KALOS_TOKEN_EQ_LEFT_SHIFT; }
yy165:
	++(*s);
	{ return KALOS_TOKEN_EQ_RIGHT_SHIFT; }
yy167:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy168;
	}
yy168:
	{ return KALOS_TOKEN_ANY; }
yy169:
	yych = *++(*s);
	switch (yych) {
	case 'l':	goto yy200;
	default:	goto yy52;
	}
yy170:
	yych = *++(*s);
	switch (yych) {
	case 'a':	goto yy202;
	default:	goto yy52;
	}
yy171:
	yych = *++(*s);
	switch (yych) {
	case 's':	goto yy203;
	case 't':	goto yy204;
	default:	goto yy52;
	}
yy172:
	yych = *++(*s);
	switch (yych) {
	case 'u':	goto yy205;
	default:	goto yy52;
	}
yy173:
	yych = *++(*s);
	switch (yych) {
	case 'p':	goto yy206;
	default:	goto yy52;
	}
yy174:
	yych = *++(*s);
	switch (yych) {
	case 'e':	goto yy207;
	default:	goto yy52;
	}
yy175:
	yych = *++(*s);
	switch (yych) {
	case 's':	goto yy209;
	default:	goto yy52;
	}
yy176:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy177;
	}
yy177:
	{ return KALOS_TOKEN_FOR; }
yy178:
	yych = *++(*s);
	switch (yych) {
	case 'd':	goto yy210;
	default:	goto yy52;
	}
yy179:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy180;
	}
yy180:
	{ return KALOS_TOKEN_IDL; }
yy181:
	yych = *++(*s);
	switch (yych) {
	case 'o':	goto yy211;
	default:	goto yy52;
	}
yy182:
	yych = *++(*s);
	switch (yych) {
	case 'e':	goto yy212;
	default:	goto yy52;
	}
yy183:
	yych = *++(*s);
	switch (yych) {
	case 'p':	goto yy213;
	default:	goto yy52;
	}
yy184:
	yych = *++(*s);
	switch (yych) {
	case 'u':	goto yy215;
	default:	goto yy52;
	}
yy185:
	yych = *++(*s);
	switch (yych) {
	case 'e':	goto yy216;
	default:	goto yy52;
	}
yy186:
	yych = *++(*s);
	switch (yych) {
	case 'b':	goto yy218;
	default:	goto yy52;
	}
yy187:
	yych = *++(*s);
	switch (yych) {
	case 'e':	goto yy219;
	default:	goto yy52;
	}
yy188:
	yych = *++(*s);
	switch (yych) {
	case 'f':	goto yy220;
	default:	goto yy52;
	}
yy189:
	yych = *++(*s);
	switch (yych) {
	case 'p':	goto yy221;
	default:	goto yy52;
	}
yy190:
	yych = *++(*s);
	switch (yych) {
	case 'd':	goto yy223;
	default:	goto yy52;
	}
yy191:
	yych = *++(*s);
	switch (yych) {
	case 'u':	goto yy225;
	default:	goto yy52;
	}
yy192:
	yych = *++(*s);
	switch (yych) {
	case 'i':	goto yy226;
	default:	goto yy52;
	}
yy193:
	yych = *++(*s);
	switch (yych) {
	case 'e':	goto yy227;
	default:	goto yy52;
	}
yy194:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy195;
	}
yy195:
	{ return KALOS_TOKEN_VAR; }
yy196:
	yych = *++(*s);
	switch (yych) {
	case 'd':	goto yy229;
	default:	goto yy52;
	}
yy197:
	yych = *++(*s);
	switch (yych) {
	case 't':	goto yy231;
	default:	goto yy52;
	}
yy198:
	++(*s);
	{ return KALOS_TOKEN_EQ_LOGOR; }
yy200:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy201;
	}
yy201:
	{ return KALOS_TOKEN_BOOL; }
yy202:
	yych = *++(*s);
	switch (yych) {
	case 'k':	goto yy232;
	default:	goto yy52;
	}
yy203:
	yych = *++(*s);
	switch (yych) {
	case 't':	goto yy234;
	default:	goto yy52;
	}
yy204:
	yych = *++(*s);
	switch (yych) {
	case 'i':	goto yy236;
	default:	goto yy52;
	}
yy205:
	yych = *++(*s);
	switch (yych) {
	case 'g':	goto yy237;
	default:	goto yy52;
	}
yy206:
	yych = *++(*s);
	switch (yych) {
	case 'a':	goto yy238;
	default:	goto yy52;
	}
yy207:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy208;
	}
yy208:
	{ return KALOS_TOKEN_ELSE; }
yy209:
	yych = *++(*s);
	switch (yych) {
	case 'e':	goto yy239;
	default:	goto yy52;
	}
yy210:
	yych = *++(*s);
	switch (yych) {
	case 'l':	goto yy241;
	default:	goto yy52;
	}
yy211:
	yych = *++(*s);
	switch (yych) {
	case 'r':	goto yy242;
	default:	goto yy52;
	}
yy212:
	yych = *++(*s);
	switch (yych) {
	case 'r':	goto yy243;
	default:	goto yy52;
	}
yy213:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy214;
	}
yy214:
	{ return KALOS_TOKEN_LOOP; }
yy215:
	yych = *++(*s);
	switch (yych) {
	case 'l':	goto yy244;
	default:	goto yy52;
	}
yy216:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy217;
	}
yy217:
	{ return KALOS_TOKEN_NAME; }
yy218:
	yych = *++(*s);
	switch (yych) {
	case 'e':	goto yy245;
	default:	goto yy52;
	}
yy219:
	yych = *++(*s);
	switch (yych) {
	case 'c':	goto yy246;
	default:	goto yy52;
	}
yy220:
	yych = *++(*s);
	switch (yych) {
	case 'i':	goto yy247;
	default:	goto yy52;
	}
yy221:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy222;
	}
yy222:
	{ return KALOS_TOKEN_PROP; }
yy223:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy224;
	}
yy224:
	{ return KALOS_TOKEN_READ; }
yy225:
	yych = *++(*s);
	switch (yych) {
	case 'r':	goto yy248;
	default:	goto yy52;
	}
yy226:
	yych = *++(*s);
	switch (yych) {
	case 'n':	goto yy249;
	default:	goto yy52;
	}
yy227:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy228;
	}
yy228:
	{ return KALOS_TOKEN_TRUE; }
yy229:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy230;
	}
yy230:
	{ return KALOS_TOKEN_VOID; }
yy231:
	yych = *++(*s);
	switch (yych) {
	case 'e':	goto yy250;
	default:	goto yy52;
	}
yy232:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy233;
	}
yy233:
	{ return KALOS_TOKEN_BREAK; }
yy234:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy235;
	}
yy235:
	{ return KALOS_TOKEN_CONST; }
yy236:
	yych = *++(*s);
	switch (yych) {
	case 'n':	goto yy252;
	default:	goto yy52;
	}
yy237:
	yych = *++(*s);
	switch (yych) {
	case 'g':	goto yy253;
	default:	goto yy52;
	}
yy238:
	yych = *++(*s);
	switch (yych) {
	case 't':	goto yy254;
	default:	goto yy52;
	}
yy239:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy240;
	}
yy240:
	{ return KALOS_TOKEN_FALSE; }
yy241:
	yych = *++(*s);
	switch (yych) {
	case 'e':	goto yy255;
	default:	goto yy52;
	}
yy242:
	yych = *++(*s);
	switch (yych) {
	case 't':	goto yy256;
	default:	goto yy52;
	}
yy243:
	yych = *++(*s);
	switch (yych) {
	case 'n':	goto yy258;
	default:	goto yy52;
	}
yy244:
	yych = *++(*s);
	switch (yych) {
	case 'e':	goto yy259;
	default:	goto yy52;
	}
yy245:
	yych = *++(*s);
	switch (yych) {
	case 'r':	goto yy261;
	default:	goto yy52;
	}
yy246:
	yych = *++(*s);
	switch (yych) {
	case 't':	goto yy263;
	default:	goto yy52;
	}
yy247:
	yych = *++(*s);
	switch (yych) {
	case 'x':	goto yy265;
	default:	goto yy52;
	}
yy248:
	yych = *++(*s);
	switch (yych) {
	case 'n':	goto yy267;
	default:	goto yy52;
	}
yy249:
	yych = *++(*s);
	switch (yych) {
	case 'g':	goto yy269;
	default:	goto yy52;
	}
yy250:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy251;
	}
yy251:
	{ return KALOS_TOKEN_WRITE; }
yy252:
	yych = *++(*s);
	switch (yych) {
	case 'u':	goto yy271;
	default:	goto yy52;
	}
yy253:
	yych = *++(*s);
	switch (yych) {
	case 'e':	goto yy272;
	default:	goto yy52;
	}
yy254:
	yych = *++(*s);
	switch (yych) {
	case 'c':	goto yy273;
	default:	goto yy52;
	}
yy255:
	yych = *++(*s);
	switch (yych) {
	case 'r':	goto yy274;
	default:	goto yy52;
	}
yy256:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy257;
	}
yy257:
	{ return KALOS_TOKEN_IMPORT; }
yy258:
	yych = *++(*s);
	switch (yych) {
	case 'a':	goto yy276;
	default:	goto yy52;
	}
yy259:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy260;
	}
yy260:
	{ return KALOS_TOKEN_MODULE; }
yy261:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy262;
	}
yy262:
	{ return KALOS_TOKEN_NUMBER; }
yy263:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy264;
	}
yy264:
	{ return KALOS_TOKEN_OBJECT; }
yy265:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy266;
	}
yy266:
	{ return KALOS_TOKEN_PREFIX; }
yy267:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy268;
	}
yy268:
	{ return KALOS_TOKEN_RETURN; }
yy269:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy270;
	}
yy270:
	{ return KALOS_TOKEN_STRING; }
yy271:
	yych = *++(*s);
	switch (yych) {
	case 'e':	goto yy277;
	default:	goto yy52;
	}
yy272:
	yych = *++(*s);
	switch (yych) {
	case 'r':	goto yy279;
	default:	goto yy52;
	}
yy273:
	yych = *++(*s);
	switch (yych) {
	case 'h':	goto yy281;
	default:	goto yy52;
	}
yy274:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy275;
	}
yy275:
	{ return KALOS_TOKEN_HANDLER; }
yy276:
	yych = *++(*s);
	switch (yych) {
	case 'l':	goto yy283;
	default:	goto yy52;
	}
yy277:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy278;
	}
yy278:
	{ return KALOS_TOKEN_CONTINUE; }
yy279:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy280;
	}
yy280:
	{ return KALOS_TOKEN_DEBUGGER; }
yy281:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy282;
	}
yy282:
	{ return KALOS_TOKEN_DISPATCH; }
yy283:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy284;
	}
yy284:
	{ return KALOS_TOKEN_INTERNAL; }
/* *********************************** */
yyc_instring:
	yych = *(*s);
	switch (yych) {
	case 0x00:	goto yy287;
	case '\n':
	case '\r':	goto yy291;
	case '"':	goto yy293;
	case '\\':	goto yy295;
	case '{':	goto yy296;
	case '}':	goto yy298;
	default:	goto yy289;
	}
yy287:
	++(*s);
	{ return KALOS_TOKEN_ERROR; }
yy289:
	++(*s);
yy290:
	ch = (*s) - 1;
	{ *output++ = *ch; continue; }
yy291:
	++(*s);
	{ return KALOS_TOKEN_ERROR; }
yy293:
	++(*s);
	c = yycinit;
	{ *output++ = 0; return KALOS_TOKEN_STRING_LITERAL; }
yy295:
	yych = *++(*s);
	switch (yych) {
	case '"':	goto yy299;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'o':
	case 'p':
	case 'q':
	case 's':
	case 'u':
	case 'v':
	case 'w':
	case 'y':
	case 'z':	goto yy301;
	case 'n':	goto yy303;
	case 'r':	goto yy305;
	case 't':	goto yy307;
	case 'x':	goto yy309;
	default:	goto yy290;
	}
yy296:
	yych = *++(*s);
	switch (yych) {
	case '{':	goto yy310;
	default:	goto yy297;
	}
yy297:
	{
            state->string_interp_state = STRING_STATE_EXPR;
            state->string_interp_mode = c;
            *output++ = 0;
            return KALOS_TOKEN_STRING_INTERPOLATION;
        }
yy298:
	yych = *++(*s);
	switch (yych) {
	case '}':	goto yy312;
	default:	goto yy290;
	}
yy299:
	++(*s);
	{ *output++ = '"'; continue; }
yy301:
	++(*s);
yy302:
	{ return KALOS_TOKEN_ERROR; }
yy303:
	++(*s);
	{ *output++ = '\n'; continue; }
yy305:
	++(*s);
	{ *output++ = '\r'; continue; }
yy307:
	++(*s);
	{ *output++ = '\t'; continue; }
yy309:
	yych = *(YYMARKER = ++(*s));
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy314;
	default:	goto yy302;
	}
yy310:
	++(*s);
	{ *output++ = '{'; continue; }
yy312:
	++(*s);
	{ *output++ = '}'; continue; }
yy314:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy316;
	default:	goto yy315;
	}
yy315:
	(*s) = YYMARKER;
	goto yy302;
yy316:
	++(*s);
	ch = (*s) - 2;
	{ char n[3] = { ch[0], ch[1], 0 }; *output++ = (char)strtol(n, NULL, 16); continue; }
/* *********************************** */
yyc_instringmulti:
	yych = *(*s);
	switch (yych) {
	case 0x00:	goto yy320;
	case '\n':
	case '\r':	goto yy324;
	case '"':	goto yy326;
	case '\\':	goto yy327;
	case '{':	goto yy328;
	case '}':	goto yy330;
	default:	goto yy322;
	}
yy320:
	++(*s);
	{ return KALOS_TOKEN_ERROR; }
yy322:
	++(*s);
yy323:
	ch = (*s) - 1;
	{ *output++ = *ch; continue; }
yy324:
	++(*s);
	ch = (*s) - 1;
	{ *output++ = *ch; continue; }
yy326:
	yych = *++(*s);
	switch (yych) {
	case '"':	goto yy333;
	default:	goto yy331;
	}
yy327:
	yych = *++(*s);
	switch (yych) {
	case '"':	goto yy334;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'o':
	case 'p':
	case 'q':
	case 's':
	case 'u':
	case 'v':
	case 'w':
	case 'y':
	case 'z':	goto yy336;
	case 'n':	goto yy338;
	case 'r':	goto yy340;
	case 't':	goto yy342;
	case 'x':	goto yy344;
	default:	goto yy323;
	}
yy328:
	yych = *++(*s);
	switch (yych) {
	case '{':	goto yy345;
	default:	goto yy329;
	}
yy329:
	{
            state->string_interp_state = STRING_STATE_EXPR;
            state->string_interp_mode = c;
            *output++ = 0;
            return KALOS_TOKEN_STRING_INTERPOLATION;
        }
yy330:
	yych = *++(*s);
	switch (yych) {
	case '}':	goto yy347;
	default:	goto yy323;
	}
yy331:
	++(*s);
	(*s) -= 1;
	ch = (*s) - 1;
	{ *output++ = '"'; continue; }
yy333:
	yych = *++(*s);
	switch (yych) {
	case '"':	goto yy351;
	default:	goto yy349;
	}
yy334:
	++(*s);
	{ *output++ = '"'; continue; }
yy336:
	++(*s);
yy337:
	{ return KALOS_TOKEN_ERROR; }
yy338:
	++(*s);
	{ *output++ = '\n'; continue; }
yy340:
	++(*s);
	{ *output++ = '\r'; continue; }
yy342:
	++(*s);
	{ *output++ = '\t'; continue; }
yy344:
	yych = *(YYMARKER = ++(*s));
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy353;
	default:	goto yy337;
	}
yy345:
	++(*s);
	{ *output++ = '{'; continue; }
yy347:
	++(*s);
	{ *output++ = '}'; continue; }
yy349:
	++(*s);
	(*s) -= 1;
	ch = (*s) - 2;
	{ *output++ = '"'; *output++ = '"'; continue; }
yy351:
	++(*s);
	c = yycinit;
	{ *output++ = 0; return KALOS_TOKEN_STRING_LITERAL; }
yy353:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy355;
	default:	goto yy354;
	}
yy354:
	(*s) = YYMARKER;
	goto yy337;
yy355:
	++(*s);
	ch = (*s) - 2;
	{ char n[3] = { ch[0], ch[1], 0 }; *output++ = (char)strtol(n, NULL, 16); continue; }
/* *********************************** */
yyc_stringformat:
	yych = *(*s);
	switch (yych) {
	case 0x00:
	case '{':	goto yy359;
	case '}':
		yyt1 = (*s);
		goto yy362;
	default:
		yyt1 = (*s);
		goto yy361;
	}
yy359:
	++(*s);
yy360:
	{ return KALOS_TOKEN_ERROR; }
yy361:
	yych = *(YYMARKER = ++(*s));
	switch (yych) {
	case 0x00:
	case '{':	goto yy360;
	default:	goto yy365;
	}
yy362:
	++(*s);
	word_start = yyt1;
	word_end = (*s) - 1;
	{
            KALOS_COPY_TOKEN;
            output[word_end - word_start] = 0;
            state->string_interp_state = STRING_STATE_DONE;
            return KALOS_TOKEN_STRING_FORMAT_SPEC;
        }
yy364:
	yych = *++(*s);
yy365:
	switch (yych) {
	case 0x00:
	case '{':	goto yy366;
	case '}':	goto yy362;
	default:	goto yy364;
	}
yy366:
	(*s) = YYMARKER;
	goto yy360;
/* *********************************** */
yyc_comment:
	yych = *(*s);
	switch (yych) {
	case 0x00:	goto yy369;
	case '\n':	goto yy373;
	default:	goto yy371;
	}
yy369:
	++(*s);
	{ return KALOS_TOKEN_EOF; }
yy371:
	++(*s);
	{ continue; }
yy373:
	++(*s);
	c = yycinit;
	{ (*line)++; continue; }
}

    }
}
