/* Generated by re2c 2.1.1 on Sun Jun 20 19:58:36 2021 */
#include "_kalos_defines.h"
#include "_kalos_lex.h"

enum yyc_state {
    yycinit,
    yycinstring,
    yycinstringmulti,
    yyccomment,
    yycstringformat,
};

#define KALOS_TOKEN(x) #x ,
const char* kalos_token_strings[] = {
    #include "_kalos_constants.inc"
    "<invalid>",
};

enum string_state {
    STRING_STATE_NORMAL,
    STRING_STATE_EXPR,
    STRING_STATE_DONE,
};

void kalos_lex_init(const char kalos_far* s, kalos_lex_state* state) {
    state->s = s;
    state->line = 1;
    state->string_interp_state = STRING_STATE_NORMAL;
    state->string_interp_mode = yycinit;
}

kalos_token kalos_lex_peek(kalos_lex_state* state, char* output) {
    kalos_lex_state temp = *state;
    return kalos_lex(&temp, output);
}

kalos_token kalos_lex(kalos_lex_state* state, char* output) {
    enum yyc_state c = yycinit;
    if (state->string_interp_state == STRING_STATE_DONE) {
        c = state->string_interp_mode;
        state->string_interp_state = STRING_STATE_NORMAL;
    }
    const char kalos_far** s = &state->s;
    int* line = &state->line;
    *output = 0;

    const char kalos_far* word_start;
    const char kalos_far* word_end;
    const char kalos_far* ch;
    const char kalos_far* YYMARKER;

    const char kalos_far *yyt1; 
    for (;;) {
    
{
	char yych;
	unsigned int yyaccept = 0;
	switch (c) {
	case yycinit:
		goto yyc_init;
	case yycinstring:
		goto yyc_instring;
	case yycinstringmulti:
		goto yyc_instringmulti;
	case yycstringformat:
		goto yyc_stringformat;
	case yyccomment:
		goto yyc_comment;
	}
/* *********************************** */
yyc_init:
	yych = *(*s);
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case '\r':
	case ' ':	goto yy6;
	case '\n':	goto yy9;
	case '!':	goto yy11;
	case '"':	goto yy13;
	case '#':	goto yy15;
	case '%':	goto yy17;
	case '&':	goto yy19;
	case '(':	goto yy21;
	case ')':	goto yy23;
	case '*':	goto yy25;
	case '+':	goto yy27;
	case ',':	goto yy29;
	case '-':	goto yy31;
	case '.':	goto yy33;
	case '/':	goto yy35;
	case '0':
		yyt1 = (*s);
		goto yy37;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt1 = (*s);
		goto yy39;
	case ':':	goto yy41;
	case ';':	goto yy43;
	case '<':	goto yy45;
	case '=':	goto yy47;
	case '>':	goto yy49;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'm':
	case 'n':
	case 'p':
	case 'q':
	case 's':
	case 'u':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = (*s);
		goto yy51;
	case '[':	goto yy54;
	case ']':	goto yy56;
	case '^':	goto yy58;
	case 'b':
		yyt1 = (*s);
		goto yy60;
	case 'c':
		yyt1 = (*s);
		goto yy61;
	case 'd':
		yyt1 = (*s);
		goto yy62;
	case 'e':
		yyt1 = (*s);
		goto yy63;
	case 'f':
		yyt1 = (*s);
		goto yy64;
	case 'i':
		yyt1 = (*s);
		goto yy65;
	case 'l':
		yyt1 = (*s);
		goto yy66;
	case 'o':
		yyt1 = (*s);
		goto yy67;
	case 'r':
		yyt1 = (*s);
		goto yy68;
	case 't':
		yyt1 = (*s);
		goto yy69;
	case 'v':
		yyt1 = (*s);
		goto yy70;
	case '{':	goto yy71;
	case '|':	goto yy73;
	case '}':	goto yy75;
	case '~':	goto yy77;
	default:	goto yy4;
	}
yy2:
	++(*s);
	{ return KALOS_TOKEN_EOF; }
yy4:
	++(*s);
	{ return KALOS_TOKEN_ERROR; }
yy6:
	yych = *++(*s);
	switch (yych) {
	case '\t':
	case '\r':
	case ' ':	goto yy6;
	default:	goto yy8;
	}
yy8:
	{ continue; }
yy9:
	++(*s);
	{ if (state->string_interp_state != STRING_STATE_NORMAL) return KALOS_TOKEN_ERROR; (*line)++; continue; }
yy11:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy79;
	default:	goto yy12;
	}
yy12:
	{ return KALOS_TOKEN_BANG; }
yy13:
	yyaccept = 0;
	yych = *(YYMARKER = ++(*s));
	switch (yych) {
	case '"':	goto yy81;
	default:	goto yy14;
	}
yy14:
	c = yycinstring;
	goto yyc_instring;
yy15:
	++(*s);
	c = yyccomment;
	goto yyc_comment;
yy17:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy83;
	default:	goto yy18;
	}
yy18:
	{ return KALOS_TOKEN_PERCENT; }
yy19:
	yych = *++(*s);
	switch (yych) {
	case '&':	goto yy85;
	case '=':	goto yy87;
	default:	goto yy20;
	}
yy20:
	{ return KALOS_TOKEN_BITAND; }
yy21:
	++(*s);
	{ return KALOS_TOKEN_PAREN_OPEN; }
yy23:
	++(*s);
	{ return KALOS_TOKEN_PAREN_CLOSE; }
yy25:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy89;
	default:	goto yy26;
	}
yy26:
	{ return KALOS_TOKEN_STAR; }
yy27:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy91;
	default:	goto yy28;
	}
yy28:
	{ return KALOS_TOKEN_PLUS; }
yy29:
	++(*s);
	{ return KALOS_TOKEN_COMMA; }
yy31:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy93;
	default:	goto yy32;
	}
yy32:
	{ return KALOS_TOKEN_MINUS; }
yy33:
	++(*s);
	{ return KALOS_TOKEN_PERIOD; }
yy35:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy95;
	default:	goto yy36;
	}
yy36:
	{ return KALOS_TOKEN_SLASH; }
yy37:
	yyaccept = 1;
	yych = *(YYMARKER = ++(*s));
	switch (yych) {
	case 'X':
	case 'x':	goto yy97;
	default:	goto yy38;
	}
yy38:
	word_start = yyt1;
	word_end = (*s);
	{ kalos_lex_strncpy(output, word_start, word_end - word_start); output[word_end - word_start] = 0; return KALOS_TOKEN_INTEGER; }
yy39:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy39;
	default:	goto yy38;
	}
yy41:
	++(*s);
	{
            if (state->string_interp_state == STRING_STATE_EXPR) {
                c = yycstringformat;
                continue;
            }
            return KALOS_TOKEN_COLON;
        }
yy43:
	++(*s);
	{ return KALOS_TOKEN_SEMI; }
yy45:
	yych = *++(*s);
	switch (yych) {
	case '<':	goto yy98;
	case '=':	goto yy100;
	default:	goto yy46;
	}
yy46:
	{ return KALOS_TOKEN_LT; }
yy47:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy102;
	default:	goto yy48;
	}
yy48:
	{ return KALOS_TOKEN_EQ; }
yy49:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy104;
	case '>':	goto yy106;
	default:	goto yy50;
	}
yy50:
	{ return KALOS_TOKEN_GT; }
yy51:
	yych = *++(*s);
yy52:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy53;
	}
yy53:
	word_start = yyt1;
	word_end = (*s);
	{ kalos_lex_strncpy(output, word_start, word_end - word_start); output[word_end - word_start] = 0; return KALOS_TOKEN_WORD; }
yy54:
	++(*s);
	{ return KALOS_TOKEN_SQBRA_OPEN; }
yy56:
	++(*s);
	{ return KALOS_TOKEN_SQBRA_CLOSE; }
yy58:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy108;
	default:	goto yy59;
	}
yy59:
	{ return KALOS_TOKEN_BITXOR; }
yy60:
	yych = *++(*s);
	switch (yych) {
	case 'r':	goto yy110;
	default:	goto yy52;
	}
yy61:
	yych = *++(*s);
	switch (yych) {
	case 'o':	goto yy111;
	default:	goto yy52;
	}
yy62:
	yych = *++(*s);
	switch (yych) {
	case 'e':	goto yy112;
	default:	goto yy52;
	}
yy63:
	yych = *++(*s);
	switch (yych) {
	case 'l':	goto yy113;
	default:	goto yy52;
	}
yy64:
	yych = *++(*s);
	switch (yych) {
	case 'a':	goto yy114;
	case 'o':	goto yy115;
	default:	goto yy52;
	}
yy65:
	yych = *++(*s);
	switch (yych) {
	case 'f':	goto yy116;
	case 'm':	goto yy118;
	case 'n':	goto yy119;
	default:	goto yy52;
	}
yy66:
	yych = *++(*s);
	switch (yych) {
	case 'o':	goto yy121;
	default:	goto yy52;
	}
yy67:
	yych = *++(*s);
	switch (yych) {
	case 'n':	goto yy122;
	default:	goto yy52;
	}
yy68:
	yych = *++(*s);
	switch (yych) {
	case 'e':	goto yy124;
	default:	goto yy52;
	}
yy69:
	yych = *++(*s);
	switch (yych) {
	case 'r':	goto yy125;
	default:	goto yy52;
	}
yy70:
	yych = *++(*s);
	switch (yych) {
	case 'a':	goto yy126;
	default:	goto yy52;
	}
yy71:
	++(*s);
	{ return KALOS_TOKEN_BRA_OPEN; }
yy73:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy127;
	case '|':	goto yy129;
	default:	goto yy74;
	}
yy74:
	{ return KALOS_TOKEN_BITOR; }
yy75:
	++(*s);
	{
            if (state->string_interp_state == STRING_STATE_EXPR) { 
                state->string_interp_state = STRING_STATE_DONE;
                output[0] = 0; // empty format spec
                return KALOS_TOKEN_STRING_FORMAT_SPEC;
            }
            return KALOS_TOKEN_BRA_CLOSE; 
        }
yy77:
	++(*s);
	{ return KALOS_TOKEN_TILDE; }
yy79:
	++(*s);
	{ return KALOS_TOKEN_NOTEQ; }
yy81:
	yych = *++(*s);
	switch (yych) {
	case '"':	goto yy131;
	default:	goto yy82;
	}
yy82:
	(*s) = YYMARKER;
	if (yyaccept == 0) {
		goto yy14;
	} else {
		goto yy38;
	}
yy83:
	++(*s);
	{ return KALOS_TOKEN_EQ_PERCENT; }
yy85:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy133;
	default:	goto yy86;
	}
yy86:
	{ return KALOS_TOKEN_LOGAND; }
yy87:
	++(*s);
	{ return KALOS_TOKEN_EQ_BITAND; }
yy89:
	++(*s);
	{ return KALOS_TOKEN_EQ_STAR; }
yy91:
	++(*s);
	{ return KALOS_TOKEN_EQ_PLUS; }
yy93:
	++(*s);
	{ return KALOS_TOKEN_EQ_MINUS; }
yy95:
	++(*s);
	{ return KALOS_TOKEN_EQ_SLASH; }
yy97:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy135;
	default:	goto yy82;
	}
yy98:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy137;
	default:	goto yy99;
	}
yy99:
	{ return KALOS_TOKEN_LEFT_SHIFT; }
yy100:
	++(*s);
	{ return KALOS_TOKEN_LTE; }
yy102:
	++(*s);
	{ return KALOS_TOKEN_EQEQ; }
yy104:
	++(*s);
	{ return KALOS_TOKEN_GTE; }
yy106:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy139;
	default:	goto yy107;
	}
yy107:
	{ return KALOS_TOKEN_RIGHT_SHIFT; }
yy108:
	++(*s);
	{ return KALOS_TOKEN_EQ_BITXOR; }
yy110:
	yych = *++(*s);
	switch (yych) {
	case 'e':	goto yy141;
	default:	goto yy52;
	}
yy111:
	yych = *++(*s);
	switch (yych) {
	case 'n':	goto yy142;
	default:	goto yy52;
	}
yy112:
	yych = *++(*s);
	switch (yych) {
	case 'b':	goto yy143;
	default:	goto yy52;
	}
yy113:
	yych = *++(*s);
	switch (yych) {
	case 's':	goto yy144;
	default:	goto yy52;
	}
yy114:
	yych = *++(*s);
	switch (yych) {
	case 'l':	goto yy145;
	default:	goto yy52;
	}
yy115:
	yych = *++(*s);
	switch (yych) {
	case 'r':	goto yy146;
	default:	goto yy52;
	}
yy116:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy117;
	}
yy117:
	{ return KALOS_TOKEN_IF; }
yy118:
	yych = *++(*s);
	switch (yych) {
	case 'p':	goto yy148;
	default:	goto yy52;
	}
yy119:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy120;
	}
yy120:
	{ return KALOS_TOKEN_IN; }
yy121:
	yych = *++(*s);
	switch (yych) {
	case 'o':	goto yy149;
	default:	goto yy52;
	}
yy122:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy123;
	}
yy123:
	{ return KALOS_TOKEN_HANDLE; }
yy124:
	yych = *++(*s);
	switch (yych) {
	case 't':	goto yy150;
	default:	goto yy52;
	}
yy125:
	yych = *++(*s);
	switch (yych) {
	case 'u':	goto yy151;
	default:	goto yy52;
	}
yy126:
	yych = *++(*s);
	switch (yych) {
	case 'r':	goto yy152;
	default:	goto yy52;
	}
yy127:
	++(*s);
	{ return KALOS_TOKEN_EQ_BITOR; }
yy129:
	yych = *++(*s);
	switch (yych) {
	case '=':	goto yy154;
	default:	goto yy130;
	}
yy130:
	{ return KALOS_TOKEN_LOGOR; }
yy131:
	++(*s);
	c = yycinstringmulti;
	goto yyc_instringmulti;
yy133:
	++(*s);
	{ return KALOS_TOKEN_EQ_LOGAND; }
yy135:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy135;
	default:	goto yy38;
	}
yy137:
	++(*s);
	{ return KALOS_TOKEN_EQ_LEFT_SHIFT; }
yy139:
	++(*s);
	{ return KALOS_TOKEN_EQ_RIGHT_SHIFT; }
yy141:
	yych = *++(*s);
	switch (yych) {
	case 'a':	goto yy156;
	default:	goto yy52;
	}
yy142:
	yych = *++(*s);
	switch (yych) {
	case 's':	goto yy157;
	case 't':	goto yy158;
	default:	goto yy52;
	}
yy143:
	yych = *++(*s);
	switch (yych) {
	case 'u':	goto yy159;
	default:	goto yy52;
	}
yy144:
	yych = *++(*s);
	switch (yych) {
	case 'e':	goto yy160;
	default:	goto yy52;
	}
yy145:
	yych = *++(*s);
	switch (yych) {
	case 's':	goto yy162;
	default:	goto yy52;
	}
yy146:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy147;
	}
yy147:
	{ return KALOS_TOKEN_FOR; }
yy148:
	yych = *++(*s);
	switch (yych) {
	case 'o':	goto yy163;
	default:	goto yy52;
	}
yy149:
	yych = *++(*s);
	switch (yych) {
	case 'p':	goto yy164;
	default:	goto yy52;
	}
yy150:
	yych = *++(*s);
	switch (yych) {
	case 'u':	goto yy166;
	default:	goto yy52;
	}
yy151:
	yych = *++(*s);
	switch (yych) {
	case 'e':	goto yy167;
	default:	goto yy52;
	}
yy152:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy153;
	}
yy153:
	{ return KALOS_TOKEN_VAR; }
yy154:
	++(*s);
	{ return KALOS_TOKEN_EQ_LOGOR; }
yy156:
	yych = *++(*s);
	switch (yych) {
	case 'k':	goto yy169;
	default:	goto yy52;
	}
yy157:
	yych = *++(*s);
	switch (yych) {
	case 't':	goto yy171;
	default:	goto yy52;
	}
yy158:
	yych = *++(*s);
	switch (yych) {
	case 'i':	goto yy173;
	default:	goto yy52;
	}
yy159:
	yych = *++(*s);
	switch (yych) {
	case 'g':	goto yy174;
	default:	goto yy52;
	}
yy160:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy161;
	}
yy161:
	{ return KALOS_TOKEN_ELSE; }
yy162:
	yych = *++(*s);
	switch (yych) {
	case 'e':	goto yy175;
	default:	goto yy52;
	}
yy163:
	yych = *++(*s);
	switch (yych) {
	case 'r':	goto yy177;
	default:	goto yy52;
	}
yy164:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy165;
	}
yy165:
	{ return KALOS_TOKEN_LOOP; }
yy166:
	yych = *++(*s);
	switch (yych) {
	case 'r':	goto yy178;
	default:	goto yy52;
	}
yy167:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy168;
	}
yy168:
	{ return KALOS_TOKEN_TRUE; }
yy169:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy170;
	}
yy170:
	{ return KALOS_TOKEN_BREAK; }
yy171:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy172;
	}
yy172:
	{ return KALOS_TOKEN_CONST; }
yy173:
	yych = *++(*s);
	switch (yych) {
	case 'n':	goto yy179;
	default:	goto yy52;
	}
yy174:
	yych = *++(*s);
	switch (yych) {
	case 'g':	goto yy180;
	default:	goto yy52;
	}
yy175:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy176;
	}
yy176:
	{ return KALOS_TOKEN_FALSE; }
yy177:
	yych = *++(*s);
	switch (yych) {
	case 't':	goto yy181;
	default:	goto yy52;
	}
yy178:
	yych = *++(*s);
	switch (yych) {
	case 'n':	goto yy183;
	default:	goto yy52;
	}
yy179:
	yych = *++(*s);
	switch (yych) {
	case 'u':	goto yy185;
	default:	goto yy52;
	}
yy180:
	yych = *++(*s);
	switch (yych) {
	case 'e':	goto yy186;
	default:	goto yy52;
	}
yy181:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy182;
	}
yy182:
	{ return KALOS_TOKEN_IMPORT; }
yy183:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy184;
	}
yy184:
	{ return KALOS_TOKEN_RETURN; }
yy185:
	yych = *++(*s);
	switch (yych) {
	case 'e':	goto yy187;
	default:	goto yy52;
	}
yy186:
	yych = *++(*s);
	switch (yych) {
	case 'r':	goto yy189;
	default:	goto yy52;
	}
yy187:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy188;
	}
yy188:
	{ return KALOS_TOKEN_CONTINUE; }
yy189:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy51;
	default:	goto yy190;
	}
yy190:
	{ return KALOS_TOKEN_DEBUGGER; }
/* *********************************** */
yyc_instring:
	yych = *(*s);
	switch (yych) {
	case 0x00:	goto yy193;
	case '\n':
	case '\r':	goto yy197;
	case '"':	goto yy199;
	case '\\':	goto yy201;
	case '{':	goto yy202;
	case '}':	goto yy204;
	default:	goto yy195;
	}
yy193:
	++(*s);
	{ return KALOS_TOKEN_ERROR; }
yy195:
	++(*s);
yy196:
	ch = (*s) - 1;
	{ *output++ = *ch; continue; }
yy197:
	++(*s);
	{ return KALOS_TOKEN_ERROR; }
yy199:
	++(*s);
	c = yycinit;
	{ *output++ = 0; return KALOS_TOKEN_STRING; }
yy201:
	yych = *++(*s);
	switch (yych) {
	case '"':	goto yy205;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'o':
	case 'p':
	case 'q':
	case 's':
	case 'u':
	case 'v':
	case 'w':
	case 'y':
	case 'z':	goto yy207;
	case 'n':	goto yy209;
	case 'r':	goto yy211;
	case 't':	goto yy213;
	case 'x':	goto yy215;
	default:	goto yy196;
	}
yy202:
	yych = *++(*s);
	switch (yych) {
	case '{':	goto yy216;
	default:	goto yy203;
	}
yy203:
	{
            state->string_interp_state = STRING_STATE_EXPR;
            state->string_interp_mode = c;
            *output++ = 0;
            return KALOS_TOKEN_STRING_INTERPOLATION;
        }
yy204:
	yych = *++(*s);
	switch (yych) {
	case '}':	goto yy218;
	default:	goto yy196;
	}
yy205:
	++(*s);
	{ *output++ = '"'; continue; }
yy207:
	++(*s);
yy208:
	{ return KALOS_TOKEN_ERROR; }
yy209:
	++(*s);
	{ *output++ = '\n'; continue; }
yy211:
	++(*s);
	{ *output++ = '\r'; continue; }
yy213:
	++(*s);
	{ *output++ = '\t'; continue; }
yy215:
	yych = *(YYMARKER = ++(*s));
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy220;
	default:	goto yy208;
	}
yy216:
	++(*s);
	{ *output++ = '{'; continue; }
yy218:
	++(*s);
	{ *output++ = '}'; continue; }
yy220:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy222;
	default:	goto yy221;
	}
yy221:
	(*s) = YYMARKER;
	goto yy208;
yy222:
	++(*s);
	ch = (*s) - 2;
	{ char n[3] = { ch[0], ch[1], 0 }; *output++ = (char)strtol(n, NULL, 16); continue; }
/* *********************************** */
yyc_instringmulti:
	yych = *(*s);
	switch (yych) {
	case 0x00:	goto yy226;
	case '\n':
	case '\r':	goto yy230;
	case '"':	goto yy232;
	case '\\':	goto yy233;
	case '{':	goto yy234;
	case '}':	goto yy236;
	default:	goto yy228;
	}
yy226:
	++(*s);
	{ return KALOS_TOKEN_ERROR; }
yy228:
	++(*s);
yy229:
	ch = (*s) - 1;
	{ *output++ = *ch; continue; }
yy230:
	++(*s);
	ch = (*s) - 1;
	{ *output++ = *ch; continue; }
yy232:
	yych = *++(*s);
	switch (yych) {
	case '"':	goto yy239;
	default:	goto yy237;
	}
yy233:
	yych = *++(*s);
	switch (yych) {
	case '"':	goto yy240;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'o':
	case 'p':
	case 'q':
	case 's':
	case 'u':
	case 'v':
	case 'w':
	case 'y':
	case 'z':	goto yy242;
	case 'n':	goto yy244;
	case 'r':	goto yy246;
	case 't':	goto yy248;
	case 'x':	goto yy250;
	default:	goto yy229;
	}
yy234:
	yych = *++(*s);
	switch (yych) {
	case '{':	goto yy251;
	default:	goto yy235;
	}
yy235:
	{
            state->string_interp_state = STRING_STATE_EXPR;
            state->string_interp_mode = c;
            *output++ = 0;
            return KALOS_TOKEN_STRING_INTERPOLATION;
        }
yy236:
	yych = *++(*s);
	switch (yych) {
	case '}':	goto yy253;
	default:	goto yy229;
	}
yy237:
	++(*s);
	(*s) -= 1;
	ch = (*s) - 1;
	{ *output++ = '"'; continue; }
yy239:
	yych = *++(*s);
	switch (yych) {
	case '"':	goto yy257;
	default:	goto yy255;
	}
yy240:
	++(*s);
	{ *output++ = '"'; continue; }
yy242:
	++(*s);
yy243:
	{ return KALOS_TOKEN_ERROR; }
yy244:
	++(*s);
	{ *output++ = '\n'; continue; }
yy246:
	++(*s);
	{ *output++ = '\r'; continue; }
yy248:
	++(*s);
	{ *output++ = '\t'; continue; }
yy250:
	yych = *(YYMARKER = ++(*s));
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy259;
	default:	goto yy243;
	}
yy251:
	++(*s);
	{ *output++ = '{'; continue; }
yy253:
	++(*s);
	{ *output++ = '}'; continue; }
yy255:
	++(*s);
	(*s) -= 1;
	ch = (*s) - 2;
	{ *output++ = '"'; *output++ = '"'; continue; }
yy257:
	++(*s);
	c = yycinit;
	{ *output++ = 0; return KALOS_TOKEN_STRING; }
yy259:
	yych = *++(*s);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy261;
	default:	goto yy260;
	}
yy260:
	(*s) = YYMARKER;
	goto yy243;
yy261:
	++(*s);
	ch = (*s) - 2;
	{ char n[3] = { ch[0], ch[1], 0 }; *output++ = (char)strtol(n, NULL, 16); continue; }
/* *********************************** */
yyc_stringformat:
	yych = *(*s);
	switch (yych) {
	case 0x00:
	case '{':	goto yy265;
	case '}':
		yyt1 = (*s);
		goto yy268;
	default:
		yyt1 = (*s);
		goto yy267;
	}
yy265:
	++(*s);
yy266:
	{ return KALOS_TOKEN_ERROR; }
yy267:
	yych = *(YYMARKER = ++(*s));
	switch (yych) {
	case 0x00:
	case '{':	goto yy266;
	default:	goto yy271;
	}
yy268:
	++(*s);
	word_start = yyt1;
	word_end = (*s) - 1;
	{
            kalos_lex_strncpy(output, word_start, word_end - word_start);
            output[word_end - word_start] = 0;
            state->string_interp_state = STRING_STATE_DONE;
            return KALOS_TOKEN_STRING_FORMAT_SPEC;
        }
yy270:
	yych = *++(*s);
yy271:
	switch (yych) {
	case 0x00:
	case '{':	goto yy272;
	case '}':	goto yy268;
	default:	goto yy270;
	}
yy272:
	(*s) = YYMARKER;
	goto yy266;
/* *********************************** */
yyc_comment:
	yych = *(*s);
	switch (yych) {
	case 0x00:	goto yy275;
	case '\n':	goto yy279;
	default:	goto yy277;
	}
yy275:
	++(*s);
	{ return KALOS_TOKEN_EOF; }
yy277:
	++(*s);
	{ continue; }
yy279:
	++(*s);
	c = yycinit;
	{ (*line)++; continue; }
}

    }
}
