/* Generated by re2c 2.1.1 on Sun Jun 20 16:12:12 2021 */
#include <memory.h>
#include <ctype.h>
#include "_kalos_idl_parse.h"
#include "_kalos_module.h"

// Comparison equivalent to 'unsigned == 0'
#pragma warning 136 9

enum yyc_state {
    yycinit,
    yycmodule,
    yycfunction,
    yycfcomma,
    yycfret,
    yychandle,
    yychcomma,
    yycobject,
};

const char* copy_string(char* buffer, const char* a, const char* b) {
    memcpy(buffer, a, b-a);
    buffer[b-a] = 0;
    return (const char*)buffer;
}

bool kalos_idl_parse_callback(const char* s, void* context, kalos_idl_callbacks* callbacks) {
    const char* start = s;
    const char* YYMARKER;
    const char *ws, *a, *b, *c, *d, *e, *f, *g, *h;
    enum yyc_state state = yycinit;

    char buffers[4][128];

    const char *yyt1; const char *yyt2; const char *yyt3; const char *yyt4; const char *yyt5; const char *yyt6; const char *yyt7; const char *yyt8; 

    for (;;) {
    
{
	char yych;
	unsigned int yyaccept = 0;
	switch (state) {
	case yycfcomma:
		goto yyc_fcomma;
	case yycfret:
		goto yyc_fret;
	case yycfunction:
		goto yyc_function;
	case yychandle:
		goto yyc_handle;
	case yychcomma:
		goto yyc_hcomma;
	case yycinit:
		goto yyc_init;
	case yycmodule:
		goto yyc_module;
	case yycobject:
		goto yyc_object;
	}
/* *********************************** */
yyc_fcomma:
	yych = *s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy4;
	case ')':	goto yy7;
	case ',':	goto yy9;
	default:	goto yy2;
	}
yy2:
	++s;
	{ callbacks->error(context, start, s - start); return false; }
yy4:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy4;
	default:	goto yy6;
	}
yy6:
	{ continue; }
yy7:
	++s;
	state = yycfret;
	goto yyc_fret;
yy9:
	++s;
	state = yycfunction;
	goto yyc_function;
/* *********************************** */
yyc_fret:
	yych = *s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = yyt3 = yyt4 = NULL;
		goto yy15;
	case ':':	goto yy18;
	case '=':
		yyt2 = yyt3 = yyt4 = NULL;
		goto yy19;
	default:	goto yy13;
	}
yy13:
	++s;
yy14:
	{ callbacks->error(context, start, s - start); return false; }
yy15:
	yyaccept = 0;
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy15;
	case '=':	goto yy20;
	default:	goto yy17;
	}
yy17:
	{ continue; }
yy18:
	yyaccept = 1;
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case 'a':
	case 'b':
	case 'n':
	case 'o':
	case 's':
	case 'v':	goto yy24;
	default:	goto yy14;
	}
yy19:
	yyaccept = 1;
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy21;
	default:	goto yy14;
	}
yy20:
	yych = *++s;
yy21:
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy20;
	case 'A':
	case 'B':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy31;
	case 'C':
		yyt1 = s;
		goto yy33;
	default:	goto yy22;
	}
yy22:
	s = YYMARKER;
	if (yyaccept == 0) {
		goto yy17;
	} else {
		goto yy14;
	}
yy23:
	yych = *++s;
yy24:
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy23;
	case 'a':
		yyt2 = yyt4 = s;
		goto yy25;
	case 'b':
		yyt2 = yyt4 = s;
		goto yy26;
	case 'n':
		yyt2 = yyt4 = s;
		goto yy27;
	case 'o':
		yyt2 = yyt4 = s;
		goto yy28;
	case 's':
		yyt2 = yyt4 = s;
		goto yy29;
	case 'v':
		yyt2 = yyt4 = s;
		goto yy30;
	default:	goto yy22;
	}
yy25:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy34;
	default:	goto yy22;
	}
yy26:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy35;
	default:	goto yy22;
	}
yy27:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy36;
	default:	goto yy22;
	}
yy28:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy37;
	default:	goto yy22;
	}
yy29:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy38;
	default:	goto yy22;
	}
yy30:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy39;
	default:	goto yy22;
	}
yy31:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt5 = s;
		goto yy40;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy31;
	case ';':
		yyt5 = s;
		goto yy42;
	default:	goto yy22;
	}
yy33:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt5 = s;
		goto yy44;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy31;
	case ';':
		yyt5 = s;
		goto yy42;
	default:	goto yy45;
	}
yy34:
	yych = *++s;
	switch (yych) {
	case 'y':	goto yy48;
	default:	goto yy22;
	}
yy35:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy49;
	default:	goto yy22;
	}
yy36:
	yych = *++s;
	switch (yych) {
	case 'm':	goto yy50;
	default:	goto yy22;
	}
yy37:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy51;
	default:	goto yy22;
	}
yy38:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy52;
	default:	goto yy22;
	}
yy39:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy53;
	default:	goto yy22;
	}
yy40:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy40;
	case ';':	goto yy42;
	default:	goto yy22;
	}
yy42:
	++s;
	a = yyt2;
	b = yyt3;
	c = yyt1;
	d = yyt5;
	state = yycmodule;
	{
            if (a && b) {
                copy_string(buffers[1], a, b);
            } else {
                strcpy(buffers[1], "void");
            }
            callbacks->end_function(context, buffers[0], buffers[1], copy_string(buffers[2], c, d));
            continue;
        }
yy44:
	yych = *++s;
yy45:
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy44;
	case '"':
		yyt1 = s;
		goto yy46;
	case ';':	goto yy42;
	default:	goto yy22;
	}
yy46:
	yych = *++s;
	switch (yych) {
	case 0x00:	goto yy22;
	case '"':	goto yy54;
	default:	goto yy46;
	}
yy48:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt3 = s;
		goto yy55;
	case '=':
		yyt3 = s;
		goto yy20;
	default:	goto yy22;
	}
yy49:
	yych = *++s;
	switch (yych) {
	case 'l':	goto yy48;
	default:	goto yy22;
	}
yy50:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy57;
	default:	goto yy22;
	}
yy51:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy58;
	default:	goto yy22;
	}
yy52:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy59;
	default:	goto yy22;
	}
yy53:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy48;
	default:	goto yy22;
	}
yy54:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy60;
	case ';':
		yyt2 = s;
		goto yy62;
	default:	goto yy22;
	}
yy55:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy55;
	case '=':	goto yy20;
	default:	goto yy22;
	}
yy57:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy64;
	default:	goto yy22;
	}
yy58:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy65;
	default:	goto yy22;
	}
yy59:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy66;
	default:	goto yy22;
	}
yy60:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy60;
	case ';':	goto yy62;
	default:	goto yy22;
	}
yy62:
	++s;
	a = yyt4;
	b = yyt3;
	c = yyt1;
	d = yyt2;
	state = yycmodule;
	{
            if (a && b) {
                copy_string(buffers[1], a, b);
            } else {
                strcpy(buffers[1], "void");
            }
            callbacks->end_function_c(context, buffers[0], buffers[1], copy_string(buffers[2], c, d));
            continue;
        }
yy64:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy48;
	default:	goto yy22;
	}
yy65:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy48;
	default:	goto yy22;
	}
yy66:
	yych = *++s;
	switch (yych) {
	case 'g':	goto yy48;
	default:	goto yy22;
	}
/* *********************************** */
yyc_function:
	yych = *s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy71;
	case ')':	goto yy74;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy76;
	default:	goto yy69;
	}
yy69:
	++s;
yy70:
	{ callbacks->error(context, start, s - start); return false; }
yy71:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy71;
	default:	goto yy73;
	}
yy73:
	{ continue; }
yy74:
	++s;
	state = yycfret;
	goto yyc_fret;
yy76:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy81;
	default:	goto yy70;
	}
yy77:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy77;
	case ':':	goto yy82;
	default:	goto yy79;
	}
yy79:
	s = YYMARKER;
	goto yy70;
yy80:
	yych = *++s;
yy81:
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy77;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy80;
	case ':':
		yyt2 = s;
		goto yy82;
	default:	goto yy79;
	}
yy82:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy82;
	case 'a':
		yyt3 = s;
		goto yy84;
	case 'b':
		yyt3 = s;
		goto yy85;
	case 'n':
		yyt3 = s;
		goto yy86;
	case 'o':
		yyt3 = s;
		goto yy87;
	case 's':
		yyt3 = s;
		goto yy88;
	case 'v':
		yyt3 = s;
		goto yy89;
	default:	goto yy79;
	}
yy84:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy90;
	default:	goto yy79;
	}
yy85:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy91;
	default:	goto yy79;
	}
yy86:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy92;
	default:	goto yy79;
	}
yy87:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy93;
	default:	goto yy79;
	}
yy88:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy94;
	default:	goto yy79;
	}
yy89:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy95;
	default:	goto yy79;
	}
yy90:
	yych = *++s;
	switch (yych) {
	case 'y':	goto yy96;
	default:	goto yy79;
	}
yy91:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy97;
	default:	goto yy79;
	}
yy92:
	yych = *++s;
	switch (yych) {
	case 'm':	goto yy98;
	default:	goto yy79;
	}
yy93:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy99;
	default:	goto yy79;
	}
yy94:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy100;
	default:	goto yy79;
	}
yy95:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy101;
	default:	goto yy79;
	}
yy96:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt4 = s;
		goto yy102;
	case ')':
	case ',':
		yyt5 = NULL;
		yyt4 = s;
		goto yy104;
	case '.':
		yyt4 = s;
		goto yy106;
	default:	goto yy79;
	}
yy97:
	yych = *++s;
	switch (yych) {
	case 'l':	goto yy96;
	default:	goto yy79;
	}
yy98:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy107;
	default:	goto yy79;
	}
yy99:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy108;
	default:	goto yy79;
	}
yy100:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy109;
	default:	goto yy79;
	}
yy101:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy96;
	default:	goto yy79;
	}
yy102:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy102;
	case ')':
	case ',':
		yyt5 = NULL;
		goto yy104;
	case '.':	goto yy106;
	default:	goto yy79;
	}
yy104:
	++s;
	a = yyt1;
	b = yyt2;
	c = yyt3;
	d = yyt4;
	f = yyt5;
	s -= 1;
	e = yyt5;
	if (yyt5 != NULL) e -= 3;
	state = yycfcomma;
	{
            callbacks->function_arg(context, copy_string(buffers[1], a, b), copy_string(buffers[2], c, d), e != NULL);
            continue;
        }
yy106:
	yych = *++s;
	switch (yych) {
	case '.':	goto yy110;
	default:	goto yy79;
	}
yy107:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy111;
	default:	goto yy79;
	}
yy108:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy112;
	default:	goto yy79;
	}
yy109:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy113;
	default:	goto yy79;
	}
yy110:
	yych = *++s;
	switch (yych) {
	case '.':	goto yy114;
	default:	goto yy79;
	}
yy111:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy96;
	default:	goto yy79;
	}
yy112:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy96;
	default:	goto yy79;
	}
yy113:
	yych = *++s;
	switch (yych) {
	case 'g':	goto yy96;
	default:	goto yy79;
	}
yy114:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt5 = s;
		goto yy115;
	case ')':
	case ',':
		yyt5 = s;
		goto yy104;
	default:	goto yy79;
	}
yy115:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy115;
	case ')':
	case ',':	goto yy104;
	default:	goto yy79;
	}
/* *********************************** */
yyc_handle:
	yych = *s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy121;
	case ')':	goto yy124;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy125;
	default:	goto yy119;
	}
yy119:
	++s;
yy120:
	{ callbacks->error(context, start, s - start); return false; }
yy121:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy121;
	default:	goto yy123;
	}
yy123:
	{ continue; }
yy124:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy126;
	case ';':	goto yy129;
	default:	goto yy120;
	}
yy125:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy134;
	default:	goto yy120;
	}
yy126:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy126;
	case ';':	goto yy129;
	default:	goto yy128;
	}
yy128:
	s = YYMARKER;
	goto yy120;
yy129:
	++s;
	state = yycmodule;
	{
            callbacks->end_handle(context);
        }
yy131:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy131;
	case ':':	goto yy135;
	default:	goto yy128;
	}
yy133:
	yych = *++s;
yy134:
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy131;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy133;
	case ':':
		yyt2 = s;
		goto yy135;
	default:	goto yy128;
	}
yy135:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy135;
	case 'a':
		yyt3 = s;
		goto yy137;
	case 'b':
		yyt3 = s;
		goto yy138;
	case 'n':
		yyt3 = s;
		goto yy139;
	case 'o':
		yyt3 = s;
		goto yy140;
	case 's':
		yyt3 = s;
		goto yy141;
	case 'v':
		yyt3 = s;
		goto yy142;
	default:	goto yy128;
	}
yy137:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy143;
	default:	goto yy128;
	}
yy138:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy144;
	default:	goto yy128;
	}
yy139:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy145;
	default:	goto yy128;
	}
yy140:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy146;
	default:	goto yy128;
	}
yy141:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy147;
	default:	goto yy128;
	}
yy142:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy148;
	default:	goto yy128;
	}
yy143:
	yych = *++s;
	switch (yych) {
	case 'y':	goto yy149;
	default:	goto yy128;
	}
yy144:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy150;
	default:	goto yy128;
	}
yy145:
	yych = *++s;
	switch (yych) {
	case 'm':	goto yy151;
	default:	goto yy128;
	}
yy146:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy152;
	default:	goto yy128;
	}
yy147:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy153;
	default:	goto yy128;
	}
yy148:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy154;
	default:	goto yy128;
	}
yy149:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt4 = s;
		goto yy155;
	case ')':
	case ',':
		yyt5 = NULL;
		yyt4 = s;
		goto yy157;
	case '.':
		yyt4 = s;
		goto yy159;
	default:	goto yy128;
	}
yy150:
	yych = *++s;
	switch (yych) {
	case 'l':	goto yy149;
	default:	goto yy128;
	}
yy151:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy160;
	default:	goto yy128;
	}
yy152:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy161;
	default:	goto yy128;
	}
yy153:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy162;
	default:	goto yy128;
	}
yy154:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy149;
	default:	goto yy128;
	}
yy155:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy155;
	case ')':
	case ',':
		yyt5 = NULL;
		goto yy157;
	case '.':	goto yy159;
	default:	goto yy128;
	}
yy157:
	++s;
	a = yyt1;
	b = yyt2;
	c = yyt3;
	d = yyt4;
	f = yyt5;
	s -= 1;
	e = yyt5;
	if (yyt5 != NULL) e -= 3;
	state = yychcomma;
	{
            callbacks->handle_arg(context, copy_string(buffers[1], a, b), copy_string(buffers[2], c, d), e != NULL);
            continue;
        }
yy159:
	yych = *++s;
	switch (yych) {
	case '.':	goto yy163;
	default:	goto yy128;
	}
yy160:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy164;
	default:	goto yy128;
	}
yy161:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy165;
	default:	goto yy128;
	}
yy162:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy166;
	default:	goto yy128;
	}
yy163:
	yych = *++s;
	switch (yych) {
	case '.':	goto yy167;
	default:	goto yy128;
	}
yy164:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy149;
	default:	goto yy128;
	}
yy165:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy149;
	default:	goto yy128;
	}
yy166:
	yych = *++s;
	switch (yych) {
	case 'g':	goto yy149;
	default:	goto yy128;
	}
yy167:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt5 = s;
		goto yy168;
	case ')':
	case ',':
		yyt5 = s;
		goto yy157;
	default:	goto yy128;
	}
yy168:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy168;
	case ')':
	case ',':	goto yy157;
	default:	goto yy128;
	}
/* *********************************** */
yyc_hcomma:
	yych = *s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy174;
	case ')':	goto yy177;
	case ',':	goto yy178;
	default:	goto yy172;
	}
yy172:
	++s;
yy173:
	{ callbacks->error(context, start, s - start); return false; }
yy174:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy174;
	default:	goto yy176;
	}
yy176:
	{ continue; }
yy177:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy180;
	case ';':	goto yy183;
	default:	goto yy173;
	}
yy178:
	++s;
	state = yychandle;
	goto yyc_handle;
yy180:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy180;
	case ';':	goto yy183;
	default:	goto yy182;
	}
yy182:
	s = YYMARKER;
	goto yy173;
yy183:
	++s;
	state = yycmodule;
	{
            callbacks->end_handle(context);
        }
/* *********************************** */
yyc_init:
	yych = *s;
	switch (yych) {
	case 0x00:	goto yy187;
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy191;
	case '#':	goto yy194;
	case 'd':	goto yy195;
	case 'm':	goto yy196;
	case 'p':	goto yy197;
	default:	goto yy189;
	}
yy187:
	++s;
	{ return true; }
yy189:
	++s;
yy190:
	{ callbacks->error(context, start, s - start); return false; }
yy191:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy191;
	default:	goto yy193;
	}
yy193:
	{ continue; }
yy194:
	yych = *(YYMARKER = ++s);
	if (yych <= 0x00) goto yy190;
	goto yy199;
yy195:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'i':	goto yy203;
	default:	goto yy190;
	}
yy196:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'o':	goto yy204;
	default:	goto yy190;
	}
yy197:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'r':	goto yy205;
	default:	goto yy190;
	}
yy198:
	yych = *++s;
yy199:
	switch (yych) {
	case 0x00:	goto yy200;
	case '\n':	goto yy201;
	default:	goto yy198;
	}
yy200:
	s = YYMARKER;
	goto yy190;
yy201:
	++s;
	{ /* comment */ continue; }
yy203:
	yych = *++s;
	switch (yych) {
	case 's':	goto yy206;
	default:	goto yy200;
	}
yy204:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy207;
	default:	goto yy200;
	}
yy205:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy208;
	default:	goto yy200;
	}
yy206:
	yych = *++s;
	switch (yych) {
	case 'p':	goto yy209;
	default:	goto yy200;
	}
yy207:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy210;
	default:	goto yy200;
	}
yy208:
	yych = *++s;
	switch (yych) {
	case 'f':	goto yy211;
	default:	goto yy200;
	}
yy209:
	yych = *++s;
	switch (yych) {
	case 'a':	goto yy212;
	default:	goto yy200;
	}
yy210:
	yych = *++s;
	switch (yych) {
	case 'l':	goto yy213;
	default:	goto yy200;
	}
yy211:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy214;
	default:	goto yy200;
	}
yy212:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy215;
	default:	goto yy200;
	}
yy213:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy216;
	default:	goto yy200;
	}
yy214:
	yych = *++s;
	switch (yych) {
	case 'x':	goto yy217;
	default:	goto yy200;
	}
yy215:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy219;
	default:	goto yy200;
	}
yy216:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy220;
	default:	goto yy200;
	}
yy217:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy217;
	case '"':
		yyt1 = s;
		goto yy222;
	default:	goto yy200;
	}
yy219:
	yych = *++s;
	switch (yych) {
	case 'h':	goto yy224;
	default:	goto yy200;
	}
yy220:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy220;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy226;
	default:	goto yy200;
	}
yy222:
	yych = *++s;
	switch (yych) {
	case 0x00:	goto yy200;
	case '"':	goto yy228;
	default:	goto yy222;
	}
yy224:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy224;
	case 'n':	goto yy229;
	default:	goto yy200;
	}
yy226:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy230;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy226;
	case '{':
		yyt2 = s;
		goto yy232;
	default:	goto yy200;
	}
yy228:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy234;
	case ';':
		yyt2 = s;
		goto yy236;
	default:	goto yy200;
	}
yy229:
	yych = *++s;
	switch (yych) {
	case 'a':	goto yy238;
	default:	goto yy200;
	}
yy230:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy230;
	case '{':	goto yy232;
	default:	goto yy200;
	}
yy232:
	++s;
	a = yyt1;
	b = yyt2;
	state = yycmodule;
	{ callbacks->begin_module(context, copy_string(buffers[0], a, b)); continue; }
yy234:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy234;
	case ';':	goto yy236;
	default:	goto yy200;
	}
yy236:
	++s;
	a = yyt1;
	b = yyt2;
	{ if (!callbacks->prefix(context, copy_string(buffers[0], a, b))) return false; continue; }
yy238:
	yych = *++s;
	switch (yych) {
	case 'm':	goto yy239;
	default:	goto yy200;
	}
yy239:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy240;
	default:	goto yy200;
	}
yy240:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy240;
	case ';':	goto yy242;
	default:	goto yy200;
	}
yy242:
	++s;
	{ callbacks->dispatch_name(context); }
/* *********************************** */
yyc_module:
	yych = *s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy248;
	case '#':	goto yy251;
	case 'c':	goto yy252;
	case 'f':	goto yy253;
	case 'h':	goto yy254;
	case 'o':	goto yy255;
	case 'p':	goto yy256;
	case '}':	goto yy257;
	default:	goto yy246;
	}
yy246:
	++s;
yy247:
	{ callbacks->error(context, start, s - start); return false; }
yy248:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy248;
	default:	goto yy250;
	}
yy250:
	{ continue; }
yy251:
	yych = *(YYMARKER = ++s);
	if (yych <= 0x00) goto yy247;
	goto yy260;
yy252:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'o':	goto yy264;
	default:	goto yy247;
	}
yy253:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'n':	goto yy265;
	default:	goto yy247;
	}
yy254:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'a':	goto yy266;
	default:	goto yy247;
	}
yy255:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'b':	goto yy267;
	default:	goto yy247;
	}
yy256:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'r':	goto yy268;
	default:	goto yy247;
	}
yy257:
	++s;
	state = yycinit;
	{ callbacks->end_module(context); continue; }
yy259:
	yych = *++s;
yy260:
	switch (yych) {
	case 0x00:	goto yy261;
	case '\n':	goto yy262;
	default:	goto yy259;
	}
yy261:
	s = YYMARKER;
	goto yy247;
yy262:
	++s;
	{ /* comment */ continue; }
yy264:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy269;
	default:	goto yy261;
	}
yy265:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy270;
	default:	goto yy261;
	}
yy266:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy272;
	default:	goto yy261;
	}
yy267:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy273;
	default:	goto yy261;
	}
yy268:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy274;
	default:	goto yy261;
	}
yy269:
	yych = *++s;
	switch (yych) {
	case 's':	goto yy275;
	default:	goto yy261;
	}
yy270:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy270;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy276;
	default:	goto yy261;
	}
yy272:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy278;
	default:	goto yy261;
	}
yy273:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy279;
	default:	goto yy261;
	}
yy274:
	yych = *++s;
	switch (yych) {
	case 'p':	goto yy280;
	default:	goto yy261;
	}
yy275:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy282;
	default:	goto yy261;
	}
yy276:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy283;
	case '(':
		yyt2 = s;
		goto yy285;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy276;
	default:	goto yy261;
	}
yy278:
	yych = *++s;
	switch (yych) {
	case 'l':	goto yy288;
	default:	goto yy261;
	}
yy279:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy289;
	default:	goto yy261;
	}
yy280:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy280;
	case '(':	goto yy290;
	default:	goto yy261;
	}
yy282:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy292;
	default:	goto yy261;
	}
yy283:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy283;
	case '(':	goto yy285;
	default:	goto yy261;
	}
yy285:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy285;
	default:	goto yy287;
	}
yy287:
	a = yyt1;
	b = yyt2;
	state = yycfunction;
	{
            copy_string(buffers[0], a, b);
            callbacks->begin_function(context, buffers[0]);
            continue;
        }
yy288:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy294;
	default:	goto yy261;
	}
yy289:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy295;
	default:	goto yy261;
	}
yy290:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy290;
	case 'r':
		yyt1 = s;
		goto yy297;
	case 'w':
		yyt1 = s;
		goto yy298;
	default:	goto yy261;
	}
yy292:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy292;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy299;
	default:	goto yy261;
	}
yy294:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy301;
	default:	goto yy261;
	}
yy295:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy295;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy303;
	default:	goto yy261;
	}
yy297:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy305;
	default:	goto yy261;
	}
yy298:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy306;
	default:	goto yy261;
	}
yy299:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy307;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy299;
	case ':':
		yyt2 = s;
		goto yy309;
	default:	goto yy261;
	}
yy301:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy301;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy311;
	default:	goto yy261;
	}
yy303:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy313;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy303;
	case '{':
		yyt2 = s;
		goto yy315;
	default:	goto yy261;
	}
yy305:
	yych = *++s;
	switch (yych) {
	case 'a':	goto yy317;
	default:	goto yy261;
	}
yy306:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy318;
	default:	goto yy261;
	}
yy307:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy307;
	case ':':	goto yy309;
	default:	goto yy261;
	}
yy309:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy309;
	case 'a':
		yyt3 = s;
		goto yy319;
	case 'b':
		yyt3 = s;
		goto yy320;
	case 'n':
		yyt3 = s;
		goto yy321;
	case 'o':
		yyt3 = s;
		goto yy322;
	case 's':
		yyt3 = s;
		goto yy323;
	case 'v':
		yyt3 = s;
		goto yy324;
	default:	goto yy261;
	}
yy311:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy325;
	case '(':
		yyt2 = s;
		goto yy327;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy311;
	case ';':	goto yy330;
	default:	goto yy261;
	}
yy313:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy313;
	case '{':	goto yy315;
	default:	goto yy261;
	}
yy315:
	++s;
	a = yyt1;
	b = yyt2;
	state = yycobject;
	{ callbacks->begin_object(context, copy_string(buffers[0], a, b)); continue; }
yy317:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy332;
	default:	goto yy261;
	}
yy318:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy333;
	default:	goto yy261;
	}
yy319:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy334;
	default:	goto yy261;
	}
yy320:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy335;
	default:	goto yy261;
	}
yy321:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy336;
	default:	goto yy261;
	}
yy322:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy337;
	default:	goto yy261;
	}
yy323:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy338;
	default:	goto yy261;
	}
yy324:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy339;
	default:	goto yy261;
	}
yy325:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy325;
	case '(':	goto yy327;
	default:	goto yy261;
	}
yy327:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy327;
	default:	goto yy329;
	}
yy329:
	a = yyt1;
	b = yyt2;
	state = yychandle;
	{
            copy_string(buffers[0], a, b);
            callbacks->begin_handle(context, buffers[0]);
            continue;
        }
yy330:
	++s;
	a = yyt1;
	b = s - 1;
	{
            copy_string(buffers[0], a, b);
            callbacks->begin_handle(context, buffers[0]);
            callbacks->end_handle(context);
            continue;
        }
yy332:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt8 = s;
		goto yy340;
	case ')':
		yyt8 = s;
		goto yy342;
	default:	goto yy341;
	}
yy333:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy346;
	default:	goto yy261;
	}
yy334:
	yych = *++s;
	switch (yych) {
	case 'y':	goto yy347;
	default:	goto yy261;
	}
yy335:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy348;
	default:	goto yy261;
	}
yy336:
	yych = *++s;
	switch (yych) {
	case 'm':	goto yy349;
	default:	goto yy261;
	}
yy337:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy350;
	default:	goto yy261;
	}
yy338:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy351;
	default:	goto yy261;
	}
yy339:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy352;
	default:	goto yy261;
	}
yy340:
	yych = *++s;
yy341:
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy340;
	case ')':	goto yy342;
	case ',':	goto yy344;
	default:	goto yy261;
	}
yy342:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy342;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt2 = s;
		goto yy353;
	default:	goto yy261;
	}
yy344:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy344;
	case 'w':	goto yy355;
	default:	goto yy261;
	}
yy346:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt8 = s;
		goto yy356;
	case ')':
		yyt8 = s;
		goto yy342;
	default:	goto yy261;
	}
yy347:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt4 = s;
		goto yy358;
	case '=':
		yyt4 = s;
		goto yy360;
	default:	goto yy261;
	}
yy348:
	yych = *++s;
	switch (yych) {
	case 'l':	goto yy347;
	default:	goto yy261;
	}
yy349:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy362;
	default:	goto yy261;
	}
yy350:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy363;
	default:	goto yy261;
	}
yy351:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy364;
	default:	goto yy261;
	}
yy352:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy347;
	default:	goto yy261;
	}
yy353:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt3 = s;
		goto yy365;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy353;
	case ':':
		yyt3 = s;
		goto yy367;
	default:	goto yy261;
	}
yy355:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy369;
	default:	goto yy261;
	}
yy356:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy356;
	case ')':	goto yy342;
	default:	goto yy261;
	}
yy358:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy358;
	case '=':	goto yy360;
	default:	goto yy261;
	}
yy360:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy360;
	case '"':
		yyt5 = s;
		goto yy370;
	case '-':
		yyt5 = s;
		goto yy372;
	case '0':
		yyt5 = s;
		goto yy373;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt5 = s;
		goto yy374;
	default:	goto yy261;
	}
yy362:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy376;
	default:	goto yy261;
	}
yy363:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy377;
	default:	goto yy261;
	}
yy364:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy378;
	default:	goto yy261;
	}
yy365:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy365;
	case ':':	goto yy367;
	default:	goto yy261;
	}
yy367:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy367;
	case 'a':
		yyt4 = s;
		goto yy379;
	case 'b':
		yyt4 = s;
		goto yy380;
	case 'n':
		yyt4 = s;
		goto yy381;
	case 'o':
		yyt4 = s;
		goto yy382;
	case 's':
		yyt4 = s;
		goto yy383;
	case 'v':
		yyt4 = s;
		goto yy384;
	default:	goto yy261;
	}
yy369:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy385;
	default:	goto yy261;
	}
yy370:
	yych = *++s;
	switch (yych) {
	case 0x00:	goto yy261;
	case '"':	goto yy386;
	default:	goto yy370;
	}
yy372:
	yych = *++s;
	switch (yych) {
	case '0':	goto yy373;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy374;
	default:	goto yy261;
	}
yy373:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt6 = s;
		goto yy387;
	case ';':
		yyt6 = s;
		goto yy389;
	case 'x':	goto yy391;
	default:	goto yy261;
	}
yy374:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt6 = s;
		goto yy387;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy374;
	case ';':
		yyt6 = s;
		goto yy389;
	default:	goto yy261;
	}
yy376:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy347;
	default:	goto yy261;
	}
yy377:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy347;
	default:	goto yy261;
	}
yy378:
	yych = *++s;
	switch (yych) {
	case 'g':	goto yy347;
	default:	goto yy261;
	}
yy379:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy392;
	default:	goto yy261;
	}
yy380:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy393;
	default:	goto yy261;
	}
yy381:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy394;
	default:	goto yy261;
	}
yy382:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy395;
	default:	goto yy261;
	}
yy383:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy396;
	default:	goto yy261;
	}
yy384:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy397;
	default:	goto yy261;
	}
yy385:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy398;
	default:	goto yy261;
	}
yy386:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt6 = s;
		goto yy387;
	case ';':
		yyt6 = s;
		goto yy389;
	default:	goto yy261;
	}
yy387:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy387;
	case ';':	goto yy389;
	default:	goto yy261;
	}
yy389:
	++s;
	a = yyt1;
	b = yyt2;
	c = yyt3;
	d = yyt4;
	e = yyt5;
	f = yyt6;
	{
            copy_string(buffers[2], e, f);
            if (buffers[2][0] == '"') {
                if (!callbacks->constant_string(context, copy_string(buffers[0], a, b), copy_string(buffers[1], c, d), buffers[2])) {
                    return false;
                }
            } else if (isdigit(buffers[2][0])) {
                if (buffers[2][1] == 'x') {
                    callbacks->constant_number(context, copy_string(buffers[0], a, b), copy_string(buffers[1], c, d), strtol(buffers[2]+2, NULL, 16));
                } else {
                    callbacks->constant_number(context, copy_string(buffers[0], a, b), copy_string(buffers[1], c, d), strtol(buffers[2], NULL, 10));
                }
            }
            continue;
        }
yy391:
	yych = *++s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy399;
	default:	goto yy261;
	}
yy392:
	yych = *++s;
	switch (yych) {
	case 'y':	goto yy401;
	default:	goto yy261;
	}
yy393:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy402;
	default:	goto yy261;
	}
yy394:
	yych = *++s;
	switch (yych) {
	case 'm':	goto yy403;
	default:	goto yy261;
	}
yy395:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy404;
	default:	goto yy261;
	}
yy396:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy405;
	default:	goto yy261;
	}
yy397:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy406;
	default:	goto yy261;
	}
yy398:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy407;
	default:	goto yy261;
	}
yy399:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt6 = s;
		goto yy387;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy399;
	case ';':
		yyt6 = s;
		goto yy389;
	default:	goto yy261;
	}
yy401:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt5 = s;
		goto yy409;
	case '=':
		yyt5 = s;
		goto yy411;
	default:	goto yy261;
	}
yy402:
	yych = *++s;
	switch (yych) {
	case 'l':	goto yy401;
	default:	goto yy261;
	}
yy403:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy413;
	default:	goto yy261;
	}
yy404:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy414;
	default:	goto yy261;
	}
yy405:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy415;
	default:	goto yy261;
	}
yy406:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy401;
	default:	goto yy261;
	}
yy407:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy407;
	case ')':	goto yy416;
	default:	goto yy261;
	}
yy409:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy409;
	case '=':	goto yy411;
	default:	goto yy261;
	}
yy411:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy411;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt6 = s;
		goto yy418;
	default:	goto yy261;
	}
yy413:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy420;
	default:	goto yy261;
	}
yy414:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy421;
	default:	goto yy261;
	}
yy415:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy422;
	default:	goto yy261;
	}
yy416:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy416;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy423;
	default:	goto yy261;
	}
yy418:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt7 = s;
		goto yy425;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy418;
	case ';':
		yyt7 = s;
		goto yy427;
	default:	goto yy261;
	}
yy420:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy401;
	default:	goto yy261;
	}
yy421:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy401;
	default:	goto yy261;
	}
yy422:
	yych = *++s;
	switch (yych) {
	case 'g':	goto yy401;
	default:	goto yy261;
	}
yy423:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy429;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy423;
	case ':':
		yyt2 = s;
		goto yy431;
	default:	goto yy261;
	}
yy425:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy425;
	case ';':	goto yy427;
	default:	goto yy261;
	}
yy427:
	++s;
	a = yyt1;
	b = yyt8;
	c = yyt2;
	d = yyt3;
	e = yyt4;
	f = yyt5;
	g = yyt6;
	h = yyt7;
	{
            callbacks->property(
                context,
                copy_string(buffers[0], c, d), // name
                copy_string(buffers[1], e, f), // type
                copy_string(buffers[2], a, b), // mode
                copy_string(buffers[3], g, h),
                NULL
            );
            continue;
        }
yy429:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy429;
	case ':':	goto yy431;
	default:	goto yy261;
	}
yy431:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy431;
	case 'a':
		yyt3 = s;
		goto yy433;
	case 'b':
		yyt3 = s;
		goto yy434;
	case 'n':
		yyt3 = s;
		goto yy435;
	case 'o':
		yyt3 = s;
		goto yy436;
	case 's':
		yyt3 = s;
		goto yy437;
	case 'v':
		yyt3 = s;
		goto yy438;
	default:	goto yy261;
	}
yy433:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy439;
	default:	goto yy261;
	}
yy434:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy440;
	default:	goto yy261;
	}
yy435:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy441;
	default:	goto yy261;
	}
yy436:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy442;
	default:	goto yy261;
	}
yy437:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy443;
	default:	goto yy261;
	}
yy438:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy444;
	default:	goto yy261;
	}
yy439:
	yych = *++s;
	switch (yych) {
	case 'y':	goto yy445;
	default:	goto yy261;
	}
yy440:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy446;
	default:	goto yy261;
	}
yy441:
	yych = *++s;
	switch (yych) {
	case 'm':	goto yy447;
	default:	goto yy261;
	}
yy442:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy448;
	default:	goto yy261;
	}
yy443:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy449;
	default:	goto yy261;
	}
yy444:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy450;
	default:	goto yy261;
	}
yy445:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt4 = s;
		goto yy451;
	case '=':
		yyt4 = s;
		goto yy453;
	default:	goto yy261;
	}
yy446:
	yych = *++s;
	switch (yych) {
	case 'l':	goto yy445;
	default:	goto yy261;
	}
yy447:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy455;
	default:	goto yy261;
	}
yy448:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy456;
	default:	goto yy261;
	}
yy449:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy457;
	default:	goto yy261;
	}
yy450:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy445;
	default:	goto yy261;
	}
yy451:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy451;
	case '=':	goto yy453;
	default:	goto yy261;
	}
yy453:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy453;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt5 = s;
		goto yy458;
	default:	goto yy261;
	}
yy455:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy460;
	default:	goto yy261;
	}
yy456:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy461;
	default:	goto yy261;
	}
yy457:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy462;
	default:	goto yy261;
	}
yy458:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt6 = s;
		goto yy463;
	case ',':
		yyt6 = s;
		goto yy465;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy458;
	default:	goto yy261;
	}
yy460:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy445;
	default:	goto yy261;
	}
yy461:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy445;
	default:	goto yy261;
	}
yy462:
	yych = *++s;
	switch (yych) {
	case 'g':	goto yy445;
	default:	goto yy261;
	}
yy463:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy463;
	case ',':	goto yy465;
	default:	goto yy261;
	}
yy465:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy465;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt7 = s;
		goto yy467;
	default:	goto yy261;
	}
yy467:
	yych = *++s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy467;
	case ';':
		yyt8 = s;
		goto yy469;
	default:	goto yy261;
	}
yy469:
	++s;
	a = yyt1;
	b = yyt2;
	c = yyt3;
	d = yyt4;
	e = yyt5;
	f = yyt6;
	g = yyt7;
	ws = yyt8;
	h = s - 1;
	{
            callbacks->property(
                context,
                copy_string(buffers[0], a, b),  // name
                copy_string(buffers[1], c, d), // type
                "read,write", // mode
                copy_string(buffers[2], e, f), // symbol1
                copy_string(buffers[3], g, h) // symbol2
            );
            continue;
        }
/* *********************************** */
yyc_object:
	yych = *s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy475;
	case '#':	goto yy478;
	case 'p':	goto yy479;
	case '}':	goto yy480;
	default:	goto yy473;
	}
yy473:
	++s;
yy474:
	{ callbacks->error(context, start, s - start); return false; }
yy475:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy475;
	default:	goto yy477;
	}
yy477:
	{ continue; }
yy478:
	yych = *(YYMARKER = ++s);
	if (yych <= 0x00) goto yy474;
	goto yy483;
yy479:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'r':	goto yy487;
	default:	goto yy474;
	}
yy480:
	++s;
	state = yycmodule;
	{ callbacks->end_object(context); continue; }
yy482:
	yych = *++s;
yy483:
	switch (yych) {
	case 0x00:	goto yy484;
	case '\n':	goto yy485;
	default:	goto yy482;
	}
yy484:
	s = YYMARKER;
	goto yy474;
yy485:
	++s;
	{ /* comment */ continue; }
yy487:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy488;
	default:	goto yy484;
	}
yy488:
	yych = *++s;
	switch (yych) {
	case 'p':	goto yy489;
	default:	goto yy484;
	}
yy489:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy489;
	case '(':	goto yy491;
	default:	goto yy484;
	}
yy491:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy491;
	case 'r':
		yyt1 = s;
		goto yy493;
	case 'w':
		yyt1 = s;
		goto yy494;
	default:	goto yy484;
	}
yy493:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy495;
	default:	goto yy484;
	}
yy494:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy496;
	default:	goto yy484;
	}
yy495:
	yych = *++s;
	switch (yych) {
	case 'a':	goto yy497;
	default:	goto yy484;
	}
yy496:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy498;
	default:	goto yy484;
	}
yy497:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy499;
	default:	goto yy484;
	}
yy498:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy500;
	default:	goto yy484;
	}
yy499:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt8 = s;
		goto yy501;
	case ')':
		yyt8 = s;
		goto yy503;
	default:	goto yy502;
	}
yy500:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy507;
	default:	goto yy484;
	}
yy501:
	yych = *++s;
yy502:
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy501;
	case ')':	goto yy503;
	case ',':	goto yy505;
	default:	goto yy484;
	}
yy503:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy503;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt2 = s;
		goto yy508;
	default:	goto yy484;
	}
yy505:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy505;
	case 'w':	goto yy510;
	default:	goto yy484;
	}
yy507:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt8 = s;
		goto yy511;
	case ')':
		yyt8 = s;
		goto yy503;
	default:	goto yy484;
	}
yy508:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt3 = s;
		goto yy513;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy508;
	case ':':
		yyt3 = s;
		goto yy515;
	default:	goto yy484;
	}
yy510:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy517;
	default:	goto yy484;
	}
yy511:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy511;
	case ')':	goto yy503;
	default:	goto yy484;
	}
yy513:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy513;
	case ':':	goto yy515;
	default:	goto yy484;
	}
yy515:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy515;
	case 'a':
		yyt4 = s;
		goto yy518;
	case 'b':
		yyt4 = s;
		goto yy519;
	case 'n':
		yyt4 = s;
		goto yy520;
	case 'o':
		yyt4 = s;
		goto yy521;
	case 's':
		yyt4 = s;
		goto yy522;
	case 'v':
		yyt4 = s;
		goto yy523;
	default:	goto yy484;
	}
yy517:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy524;
	default:	goto yy484;
	}
yy518:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy525;
	default:	goto yy484;
	}
yy519:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy526;
	default:	goto yy484;
	}
yy520:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy527;
	default:	goto yy484;
	}
yy521:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy528;
	default:	goto yy484;
	}
yy522:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy529;
	default:	goto yy484;
	}
yy523:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy530;
	default:	goto yy484;
	}
yy524:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy531;
	default:	goto yy484;
	}
yy525:
	yych = *++s;
	switch (yych) {
	case 'y':	goto yy532;
	default:	goto yy484;
	}
yy526:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy533;
	default:	goto yy484;
	}
yy527:
	yych = *++s;
	switch (yych) {
	case 'm':	goto yy534;
	default:	goto yy484;
	}
yy528:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy535;
	default:	goto yy484;
	}
yy529:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy536;
	default:	goto yy484;
	}
yy530:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy537;
	default:	goto yy484;
	}
yy531:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy538;
	default:	goto yy484;
	}
yy532:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt5 = s;
		goto yy540;
	case '=':
		yyt5 = s;
		goto yy542;
	default:	goto yy484;
	}
yy533:
	yych = *++s;
	switch (yych) {
	case 'l':	goto yy532;
	default:	goto yy484;
	}
yy534:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy544;
	default:	goto yy484;
	}
yy535:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy545;
	default:	goto yy484;
	}
yy536:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy546;
	default:	goto yy484;
	}
yy537:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy532;
	default:	goto yy484;
	}
yy538:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy538;
	case ')':	goto yy547;
	default:	goto yy484;
	}
yy540:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy540;
	case '=':	goto yy542;
	default:	goto yy484;
	}
yy542:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy542;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt6 = s;
		goto yy549;
	default:	goto yy484;
	}
yy544:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy551;
	default:	goto yy484;
	}
yy545:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy552;
	default:	goto yy484;
	}
yy546:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy553;
	default:	goto yy484;
	}
yy547:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy547;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy554;
	default:	goto yy484;
	}
yy549:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt7 = s;
		goto yy556;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy549;
	case ';':
		yyt7 = s;
		goto yy558;
	default:	goto yy484;
	}
yy551:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy532;
	default:	goto yy484;
	}
yy552:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy532;
	default:	goto yy484;
	}
yy553:
	yych = *++s;
	switch (yych) {
	case 'g':	goto yy532;
	default:	goto yy484;
	}
yy554:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy560;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy554;
	case ':':
		yyt2 = s;
		goto yy562;
	default:	goto yy484;
	}
yy556:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy556;
	case ';':	goto yy558;
	default:	goto yy484;
	}
yy558:
	++s;
	a = yyt1;
	b = yyt8;
	c = yyt2;
	d = yyt3;
	e = yyt4;
	f = yyt5;
	g = yyt6;
	h = yyt7;
	{
            callbacks->property(
                context,
                copy_string(buffers[0], c, d), // name
                copy_string(buffers[1], e, f), // type
                copy_string(buffers[2], a, b), // mode
                copy_string(buffers[3], g, h),
                NULL
            );
            continue;
        }
yy560:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy560;
	case ':':	goto yy562;
	default:	goto yy484;
	}
yy562:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy562;
	case 'a':
		yyt3 = s;
		goto yy564;
	case 'b':
		yyt3 = s;
		goto yy565;
	case 'n':
		yyt3 = s;
		goto yy566;
	case 'o':
		yyt3 = s;
		goto yy567;
	case 's':
		yyt3 = s;
		goto yy568;
	case 'v':
		yyt3 = s;
		goto yy569;
	default:	goto yy484;
	}
yy564:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy570;
	default:	goto yy484;
	}
yy565:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy571;
	default:	goto yy484;
	}
yy566:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy572;
	default:	goto yy484;
	}
yy567:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy573;
	default:	goto yy484;
	}
yy568:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy574;
	default:	goto yy484;
	}
yy569:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy575;
	default:	goto yy484;
	}
yy570:
	yych = *++s;
	switch (yych) {
	case 'y':	goto yy576;
	default:	goto yy484;
	}
yy571:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy577;
	default:	goto yy484;
	}
yy572:
	yych = *++s;
	switch (yych) {
	case 'm':	goto yy578;
	default:	goto yy484;
	}
yy573:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy579;
	default:	goto yy484;
	}
yy574:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy580;
	default:	goto yy484;
	}
yy575:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy581;
	default:	goto yy484;
	}
yy576:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt4 = s;
		goto yy582;
	case '=':
		yyt4 = s;
		goto yy584;
	default:	goto yy484;
	}
yy577:
	yych = *++s;
	switch (yych) {
	case 'l':	goto yy576;
	default:	goto yy484;
	}
yy578:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy586;
	default:	goto yy484;
	}
yy579:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy587;
	default:	goto yy484;
	}
yy580:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy588;
	default:	goto yy484;
	}
yy581:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy576;
	default:	goto yy484;
	}
yy582:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy582;
	case '=':	goto yy584;
	default:	goto yy484;
	}
yy584:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy584;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt5 = s;
		goto yy589;
	default:	goto yy484;
	}
yy586:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy591;
	default:	goto yy484;
	}
yy587:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy592;
	default:	goto yy484;
	}
yy588:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy593;
	default:	goto yy484;
	}
yy589:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt6 = s;
		goto yy594;
	case ',':
		yyt6 = s;
		goto yy596;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy589;
	default:	goto yy484;
	}
yy591:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy576;
	default:	goto yy484;
	}
yy592:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy576;
	default:	goto yy484;
	}
yy593:
	yych = *++s;
	switch (yych) {
	case 'g':	goto yy576;
	default:	goto yy484;
	}
yy594:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy594;
	case ',':	goto yy596;
	default:	goto yy484;
	}
yy596:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy596;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt7 = s;
		goto yy598;
	default:	goto yy484;
	}
yy598:
	yych = *++s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy598;
	case ';':
		yyt8 = s;
		goto yy600;
	default:	goto yy484;
	}
yy600:
	++s;
	a = yyt1;
	b = yyt2;
	c = yyt3;
	d = yyt4;
	e = yyt5;
	f = yyt6;
	g = yyt7;
	ws = yyt8;
	h = s - 1;
	{
            callbacks->property(
                context,
                copy_string(buffers[0], a, b),  // name
                copy_string(buffers[1], c, d), // type
                "read,write", // mode
                copy_string(buffers[2], e, f), // symbol1
                copy_string(buffers[3], g, h) // symbol2
            );
            continue;
        }
}

    }
}
