/* Generated by re2c 2.1.1 on Sat Jun 12 13:12:11 2021 */
#include <stdbool.h>
#include <memory.h>
#include <ctype.h>
#include "kalos_idl_parse.h"
#include "kalos_module.h"

// Comparison equivalent to 'unsigned == 0'
#pragma warning 136 9

enum yyc_state {
    yycinit,
    yycmodule,
    yycfunction,
    yycfcomma,
    yycfret,
    yychandle,
    yychcomma,
    yycobject,
};

const char* copy_string(char* buffer, const char* a, const char* b) {
    memcpy(buffer, a, b-a);
    buffer[b-a] = 0;
    return (const char*)buffer;
}

bool kalos_idl_parse_callback(const char* s, void* context, kalos_idl_callbacks* callbacks) {
    const char* start = s;
    const char* YYMARKER;
    const char *ws, *a, *b, *c, *d, *e, *f, *g, *h;
    enum yyc_state state = yycinit;

    char buffers[4][128];

    const char *yyt1; const char *yyt2; const char *yyt3; const char *yyt4; const char *yyt5; const char *yyt6; const char *yyt7; const char *yyt8; 

    for (;;) {
    
{
	char yych;
	unsigned int yyaccept = 0;
	switch (state) {
	case yycfcomma:
		goto yyc_fcomma;
	case yycfret:
		goto yyc_fret;
	case yycfunction:
		goto yyc_function;
	case yychandle:
		goto yyc_handle;
	case yychcomma:
		goto yyc_hcomma;
	case yycinit:
		goto yyc_init;
	case yycmodule:
		goto yyc_module;
	case yycobject:
		goto yyc_object;
	}
/* *********************************** */
yyc_fcomma:
	yych = *s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy4;
	case ')':	goto yy7;
	case ',':	goto yy9;
	default:	goto yy2;
	}
yy2:
	++s;
	{ callbacks->error(context, start, s - start); return false; }
yy4:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy4;
	default:	goto yy6;
	}
yy6:
	{ continue; }
yy7:
	++s;
	state = yycfret;
	goto yyc_fret;
yy9:
	++s;
	state = yycfunction;
	goto yyc_function;
/* *********************************** */
yyc_fret:
	yych = *s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt3 = yyt4 = NULL;
		goto yy15;
	case ':':	goto yy18;
	case '=':
		yyt3 = yyt4 = NULL;
		goto yy19;
	default:	goto yy13;
	}
yy13:
	++s;
yy14:
	{ callbacks->error(context, start, s - start); return false; }
yy15:
	yyaccept = 0;
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy15;
	case '=':	goto yy20;
	default:	goto yy17;
	}
yy17:
	{ continue; }
yy18:
	yyaccept = 1;
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case 'a':
	case 'b':
	case 'n':
	case 'o':
	case 's':
	case 'v':	goto yy24;
	default:	goto yy14;
	}
yy19:
	yyaccept = 1;
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy20;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy31;
	default:	goto yy14;
	}
yy20:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy20;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy31;
	default:	goto yy22;
	}
yy22:
	s = YYMARKER;
	if (yyaccept == 0) {
		goto yy17;
	} else {
		goto yy14;
	}
yy23:
	yych = *++s;
yy24:
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy23;
	case 'a':
		yyt3 = s;
		goto yy25;
	case 'b':
		yyt3 = s;
		goto yy26;
	case 'n':
		yyt3 = s;
		goto yy27;
	case 'o':
		yyt3 = s;
		goto yy28;
	case 's':
		yyt3 = s;
		goto yy29;
	case 'v':
		yyt3 = s;
		goto yy30;
	default:	goto yy22;
	}
yy25:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy33;
	default:	goto yy22;
	}
yy26:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy34;
	default:	goto yy22;
	}
yy27:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy35;
	default:	goto yy22;
	}
yy28:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy36;
	default:	goto yy22;
	}
yy29:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy37;
	default:	goto yy22;
	}
yy30:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy38;
	default:	goto yy22;
	}
yy31:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy39;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy31;
	case ';':
		yyt2 = s;
		goto yy41;
	default:	goto yy22;
	}
yy33:
	yych = *++s;
	switch (yych) {
	case 'y':	goto yy43;
	default:	goto yy22;
	}
yy34:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy44;
	default:	goto yy22;
	}
yy35:
	yych = *++s;
	switch (yych) {
	case 'm':	goto yy45;
	default:	goto yy22;
	}
yy36:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy46;
	default:	goto yy22;
	}
yy37:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy47;
	default:	goto yy22;
	}
yy38:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy48;
	default:	goto yy22;
	}
yy39:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy39;
	case ';':	goto yy41;
	default:	goto yy22;
	}
yy41:
	++s;
	a = yyt3;
	b = yyt4;
	c = yyt1;
	d = yyt2;
	state = yycmodule;
	{
            if (a && b) {
                copy_string(buffers[1], a, b);
            } else {
                strcpy(buffers[1], "void");
            }
            callbacks->end_function(context, buffers[0], buffers[1], copy_string(buffers[2], c, d));
            continue;
        }
yy43:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt4 = s;
		goto yy49;
	case '=':
		yyt4 = s;
		goto yy20;
	default:	goto yy22;
	}
yy44:
	yych = *++s;
	switch (yych) {
	case 'l':	goto yy43;
	default:	goto yy22;
	}
yy45:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy51;
	default:	goto yy22;
	}
yy46:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy52;
	default:	goto yy22;
	}
yy47:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy53;
	default:	goto yy22;
	}
yy48:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy43;
	default:	goto yy22;
	}
yy49:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy49;
	case '=':	goto yy20;
	default:	goto yy22;
	}
yy51:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy54;
	default:	goto yy22;
	}
yy52:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy55;
	default:	goto yy22;
	}
yy53:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy56;
	default:	goto yy22;
	}
yy54:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy43;
	default:	goto yy22;
	}
yy55:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy43;
	default:	goto yy22;
	}
yy56:
	yych = *++s;
	switch (yych) {
	case 'g':	goto yy43;
	default:	goto yy22;
	}
/* *********************************** */
yyc_function:
	yych = *s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy61;
	case ')':	goto yy64;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy66;
	default:	goto yy59;
	}
yy59:
	++s;
yy60:
	{ callbacks->error(context, start, s - start); return false; }
yy61:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy61;
	default:	goto yy63;
	}
yy63:
	{ continue; }
yy64:
	++s;
	state = yycfret;
	goto yyc_fret;
yy66:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy71;
	default:	goto yy60;
	}
yy67:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy67;
	case ':':	goto yy72;
	default:	goto yy69;
	}
yy69:
	s = YYMARKER;
	goto yy60;
yy70:
	yych = *++s;
yy71:
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy67;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy70;
	case ':':
		yyt2 = s;
		goto yy72;
	default:	goto yy69;
	}
yy72:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy72;
	case 'a':
		yyt3 = s;
		goto yy74;
	case 'b':
		yyt3 = s;
		goto yy75;
	case 'n':
		yyt3 = s;
		goto yy76;
	case 'o':
		yyt3 = s;
		goto yy77;
	case 's':
		yyt3 = s;
		goto yy78;
	case 'v':
		yyt3 = s;
		goto yy79;
	default:	goto yy69;
	}
yy74:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy80;
	default:	goto yy69;
	}
yy75:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy81;
	default:	goto yy69;
	}
yy76:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy82;
	default:	goto yy69;
	}
yy77:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy83;
	default:	goto yy69;
	}
yy78:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy84;
	default:	goto yy69;
	}
yy79:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy85;
	default:	goto yy69;
	}
yy80:
	yych = *++s;
	switch (yych) {
	case 'y':	goto yy86;
	default:	goto yy69;
	}
yy81:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy87;
	default:	goto yy69;
	}
yy82:
	yych = *++s;
	switch (yych) {
	case 'm':	goto yy88;
	default:	goto yy69;
	}
yy83:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy89;
	default:	goto yy69;
	}
yy84:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy90;
	default:	goto yy69;
	}
yy85:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy91;
	default:	goto yy69;
	}
yy86:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt4 = s;
		goto yy92;
	case ')':
	case ',':
		yyt5 = NULL;
		yyt4 = s;
		goto yy94;
	case '.':
		yyt4 = s;
		goto yy96;
	default:	goto yy69;
	}
yy87:
	yych = *++s;
	switch (yych) {
	case 'l':	goto yy86;
	default:	goto yy69;
	}
yy88:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy97;
	default:	goto yy69;
	}
yy89:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy98;
	default:	goto yy69;
	}
yy90:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy99;
	default:	goto yy69;
	}
yy91:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy86;
	default:	goto yy69;
	}
yy92:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy92;
	case ')':
	case ',':
		yyt5 = NULL;
		goto yy94;
	case '.':	goto yy96;
	default:	goto yy69;
	}
yy94:
	++s;
	a = yyt1;
	b = yyt2;
	c = yyt3;
	d = yyt4;
	f = yyt5;
	s -= 1;
	e = yyt5;
	if (yyt5 != NULL) e -= 3;
	state = yycfcomma;
	{
            callbacks->function_arg(context, copy_string(buffers[1], a, b), copy_string(buffers[2], c, d), e != NULL);
            continue;
        }
yy96:
	yych = *++s;
	switch (yych) {
	case '.':	goto yy100;
	default:	goto yy69;
	}
yy97:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy101;
	default:	goto yy69;
	}
yy98:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy102;
	default:	goto yy69;
	}
yy99:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy103;
	default:	goto yy69;
	}
yy100:
	yych = *++s;
	switch (yych) {
	case '.':	goto yy104;
	default:	goto yy69;
	}
yy101:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy86;
	default:	goto yy69;
	}
yy102:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy86;
	default:	goto yy69;
	}
yy103:
	yych = *++s;
	switch (yych) {
	case 'g':	goto yy86;
	default:	goto yy69;
	}
yy104:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt5 = s;
		goto yy105;
	case ')':
	case ',':
		yyt5 = s;
		goto yy94;
	default:	goto yy69;
	}
yy105:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy105;
	case ')':
	case ',':	goto yy94;
	default:	goto yy69;
	}
/* *********************************** */
yyc_handle:
	yych = *s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy111;
	case ')':	goto yy114;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy115;
	default:	goto yy109;
	}
yy109:
	++s;
yy110:
	{ callbacks->error(context, start, s - start); return false; }
yy111:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy111;
	default:	goto yy113;
	}
yy113:
	{ continue; }
yy114:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy116;
	case ';':	goto yy119;
	default:	goto yy110;
	}
yy115:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy124;
	default:	goto yy110;
	}
yy116:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy116;
	case ';':	goto yy119;
	default:	goto yy118;
	}
yy118:
	s = YYMARKER;
	goto yy110;
yy119:
	++s;
	state = yycmodule;
	{
            callbacks->end_handle(context);
        }
yy121:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy121;
	case ':':	goto yy125;
	default:	goto yy118;
	}
yy123:
	yych = *++s;
yy124:
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy121;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy123;
	case ':':
		yyt2 = s;
		goto yy125;
	default:	goto yy118;
	}
yy125:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy125;
	case 'a':
		yyt3 = s;
		goto yy127;
	case 'b':
		yyt3 = s;
		goto yy128;
	case 'n':
		yyt3 = s;
		goto yy129;
	case 'o':
		yyt3 = s;
		goto yy130;
	case 's':
		yyt3 = s;
		goto yy131;
	case 'v':
		yyt3 = s;
		goto yy132;
	default:	goto yy118;
	}
yy127:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy133;
	default:	goto yy118;
	}
yy128:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy134;
	default:	goto yy118;
	}
yy129:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy135;
	default:	goto yy118;
	}
yy130:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy136;
	default:	goto yy118;
	}
yy131:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy137;
	default:	goto yy118;
	}
yy132:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy138;
	default:	goto yy118;
	}
yy133:
	yych = *++s;
	switch (yych) {
	case 'y':	goto yy139;
	default:	goto yy118;
	}
yy134:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy140;
	default:	goto yy118;
	}
yy135:
	yych = *++s;
	switch (yych) {
	case 'm':	goto yy141;
	default:	goto yy118;
	}
yy136:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy142;
	default:	goto yy118;
	}
yy137:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy143;
	default:	goto yy118;
	}
yy138:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy144;
	default:	goto yy118;
	}
yy139:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt4 = s;
		goto yy145;
	case ')':
	case ',':
		yyt5 = NULL;
		yyt4 = s;
		goto yy147;
	case '.':
		yyt4 = s;
		goto yy149;
	default:	goto yy118;
	}
yy140:
	yych = *++s;
	switch (yych) {
	case 'l':	goto yy139;
	default:	goto yy118;
	}
yy141:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy150;
	default:	goto yy118;
	}
yy142:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy151;
	default:	goto yy118;
	}
yy143:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy152;
	default:	goto yy118;
	}
yy144:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy139;
	default:	goto yy118;
	}
yy145:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy145;
	case ')':
	case ',':
		yyt5 = NULL;
		goto yy147;
	case '.':	goto yy149;
	default:	goto yy118;
	}
yy147:
	++s;
	a = yyt1;
	b = yyt2;
	c = yyt3;
	d = yyt4;
	f = yyt5;
	s -= 1;
	e = yyt5;
	if (yyt5 != NULL) e -= 3;
	state = yychcomma;
	{
            callbacks->handle_arg(context, copy_string(buffers[1], a, b), copy_string(buffers[2], c, d), e != NULL);
            continue;
        }
yy149:
	yych = *++s;
	switch (yych) {
	case '.':	goto yy153;
	default:	goto yy118;
	}
yy150:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy154;
	default:	goto yy118;
	}
yy151:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy155;
	default:	goto yy118;
	}
yy152:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy156;
	default:	goto yy118;
	}
yy153:
	yych = *++s;
	switch (yych) {
	case '.':	goto yy157;
	default:	goto yy118;
	}
yy154:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy139;
	default:	goto yy118;
	}
yy155:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy139;
	default:	goto yy118;
	}
yy156:
	yych = *++s;
	switch (yych) {
	case 'g':	goto yy139;
	default:	goto yy118;
	}
yy157:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt5 = s;
		goto yy158;
	case ')':
	case ',':
		yyt5 = s;
		goto yy147;
	default:	goto yy118;
	}
yy158:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy158;
	case ')':
	case ',':	goto yy147;
	default:	goto yy118;
	}
/* *********************************** */
yyc_hcomma:
	yych = *s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy164;
	case ')':	goto yy167;
	case ',':	goto yy168;
	default:	goto yy162;
	}
yy162:
	++s;
yy163:
	{ callbacks->error(context, start, s - start); return false; }
yy164:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy164;
	default:	goto yy166;
	}
yy166:
	{ continue; }
yy167:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy170;
	case ';':	goto yy173;
	default:	goto yy163;
	}
yy168:
	++s;
	state = yychandle;
	goto yyc_handle;
yy170:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy170;
	case ';':	goto yy173;
	default:	goto yy172;
	}
yy172:
	s = YYMARKER;
	goto yy163;
yy173:
	++s;
	state = yycmodule;
	{
            callbacks->end_handle(context);
        }
/* *********************************** */
yyc_init:
	yych = *s;
	switch (yych) {
	case 0x00:	goto yy177;
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy181;
	case '#':	goto yy184;
	case 'm':	goto yy185;
	case 'p':	goto yy186;
	default:	goto yy179;
	}
yy177:
	++s;
	{ return true; }
yy179:
	++s;
yy180:
	{ callbacks->error(context, start, s - start); return false; }
yy181:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy181;
	default:	goto yy183;
	}
yy183:
	{ continue; }
yy184:
	yych = *(YYMARKER = ++s);
	if (yych <= 0x00) goto yy180;
	goto yy188;
yy185:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'o':	goto yy192;
	default:	goto yy180;
	}
yy186:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'r':	goto yy193;
	default:	goto yy180;
	}
yy187:
	yych = *++s;
yy188:
	switch (yych) {
	case 0x00:	goto yy189;
	case '\n':	goto yy190;
	default:	goto yy187;
	}
yy189:
	s = YYMARKER;
	goto yy180;
yy190:
	++s;
	{ /* comment */ continue; }
yy192:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy194;
	default:	goto yy189;
	}
yy193:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy195;
	default:	goto yy189;
	}
yy194:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy196;
	default:	goto yy189;
	}
yy195:
	yych = *++s;
	switch (yych) {
	case 'f':	goto yy197;
	default:	goto yy189;
	}
yy196:
	yych = *++s;
	switch (yych) {
	case 'l':	goto yy198;
	default:	goto yy189;
	}
yy197:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy199;
	default:	goto yy189;
	}
yy198:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy200;
	default:	goto yy189;
	}
yy199:
	yych = *++s;
	switch (yych) {
	case 'x':	goto yy201;
	default:	goto yy189;
	}
yy200:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy203;
	default:	goto yy189;
	}
yy201:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy201;
	case '"':
		yyt1 = s;
		goto yy205;
	default:	goto yy189;
	}
yy203:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy203;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy207;
	default:	goto yy189;
	}
yy205:
	yych = *++s;
	switch (yych) {
	case 0x00:	goto yy189;
	case '"':	goto yy209;
	default:	goto yy205;
	}
yy207:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy210;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy207;
	case '{':
		yyt2 = s;
		goto yy212;
	default:	goto yy189;
	}
yy209:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy214;
	case ';':
		yyt2 = s;
		goto yy216;
	default:	goto yy189;
	}
yy210:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy210;
	case '{':	goto yy212;
	default:	goto yy189;
	}
yy212:
	++s;
	a = yyt1;
	b = yyt2;
	state = yycmodule;
	{ callbacks->begin_module(context, copy_string(buffers[0], a, b)); continue; }
yy214:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy214;
	case ';':	goto yy216;
	default:	goto yy189;
	}
yy216:
	++s;
	a = yyt1;
	b = yyt2;
	{ if (!callbacks->prefix(context, copy_string(buffers[0], a, b))) return false; continue; }
/* *********************************** */
yyc_module:
	yych = *s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy222;
	case '#':	goto yy225;
	case 'c':	goto yy226;
	case 'f':	goto yy227;
	case 'h':	goto yy228;
	case 'o':	goto yy229;
	case 'p':	goto yy230;
	case '}':	goto yy231;
	default:	goto yy220;
	}
yy220:
	++s;
yy221:
	{ callbacks->error(context, start, s - start); return false; }
yy222:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy222;
	default:	goto yy224;
	}
yy224:
	{ continue; }
yy225:
	yych = *(YYMARKER = ++s);
	if (yych <= 0x00) goto yy221;
	goto yy234;
yy226:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'o':	goto yy238;
	default:	goto yy221;
	}
yy227:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'n':	goto yy239;
	default:	goto yy221;
	}
yy228:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'a':	goto yy240;
	default:	goto yy221;
	}
yy229:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'b':	goto yy241;
	default:	goto yy221;
	}
yy230:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'r':	goto yy242;
	default:	goto yy221;
	}
yy231:
	++s;
	state = yycinit;
	{ callbacks->end_module(context); continue; }
yy233:
	yych = *++s;
yy234:
	switch (yych) {
	case 0x00:	goto yy235;
	case '\n':	goto yy236;
	default:	goto yy233;
	}
yy235:
	s = YYMARKER;
	goto yy221;
yy236:
	++s;
	{ /* comment */ continue; }
yy238:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy243;
	default:	goto yy235;
	}
yy239:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy244;
	default:	goto yy235;
	}
yy240:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy246;
	default:	goto yy235;
	}
yy241:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy247;
	default:	goto yy235;
	}
yy242:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy248;
	default:	goto yy235;
	}
yy243:
	yych = *++s;
	switch (yych) {
	case 's':	goto yy249;
	default:	goto yy235;
	}
yy244:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy244;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy250;
	default:	goto yy235;
	}
yy246:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy252;
	default:	goto yy235;
	}
yy247:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy253;
	default:	goto yy235;
	}
yy248:
	yych = *++s;
	switch (yych) {
	case 'p':	goto yy254;
	default:	goto yy235;
	}
yy249:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy256;
	default:	goto yy235;
	}
yy250:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy257;
	case '(':
		yyt2 = s;
		goto yy259;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy250;
	default:	goto yy235;
	}
yy252:
	yych = *++s;
	switch (yych) {
	case 'l':	goto yy262;
	default:	goto yy235;
	}
yy253:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy263;
	default:	goto yy235;
	}
yy254:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy254;
	case '(':	goto yy264;
	default:	goto yy235;
	}
yy256:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy266;
	default:	goto yy235;
	}
yy257:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy257;
	case '(':	goto yy259;
	default:	goto yy235;
	}
yy259:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy259;
	default:	goto yy261;
	}
yy261:
	a = yyt1;
	b = yyt2;
	state = yycfunction;
	{
            copy_string(buffers[0], a, b);
            callbacks->begin_function(context, buffers[0]);
            continue;
        }
yy262:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy268;
	default:	goto yy235;
	}
yy263:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy269;
	default:	goto yy235;
	}
yy264:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy264;
	case 'r':
		yyt1 = s;
		goto yy271;
	case 'w':
		yyt1 = s;
		goto yy272;
	default:	goto yy235;
	}
yy266:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy266;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy273;
	default:	goto yy235;
	}
yy268:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy275;
	default:	goto yy235;
	}
yy269:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy269;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy277;
	default:	goto yy235;
	}
yy271:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy279;
	default:	goto yy235;
	}
yy272:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy280;
	default:	goto yy235;
	}
yy273:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy281;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy273;
	case ':':
		yyt2 = s;
		goto yy283;
	default:	goto yy235;
	}
yy275:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy275;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy285;
	default:	goto yy235;
	}
yy277:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy287;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy277;
	case '{':
		yyt2 = s;
		goto yy289;
	default:	goto yy235;
	}
yy279:
	yych = *++s;
	switch (yych) {
	case 'a':	goto yy291;
	default:	goto yy235;
	}
yy280:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy292;
	default:	goto yy235;
	}
yy281:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy281;
	case ':':	goto yy283;
	default:	goto yy235;
	}
yy283:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy283;
	case 'a':
		yyt3 = s;
		goto yy293;
	case 'b':
		yyt3 = s;
		goto yy294;
	case 'n':
		yyt3 = s;
		goto yy295;
	case 'o':
		yyt3 = s;
		goto yy296;
	case 's':
		yyt3 = s;
		goto yy297;
	case 'v':
		yyt3 = s;
		goto yy298;
	default:	goto yy235;
	}
yy285:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy299;
	case '(':
		yyt2 = s;
		goto yy301;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy285;
	case ';':	goto yy304;
	default:	goto yy235;
	}
yy287:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy287;
	case '{':	goto yy289;
	default:	goto yy235;
	}
yy289:
	++s;
	a = yyt1;
	b = yyt2;
	state = yycobject;
	{ callbacks->begin_object(context, copy_string(buffers[0], a, b)); continue; }
yy291:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy306;
	default:	goto yy235;
	}
yy292:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy307;
	default:	goto yy235;
	}
yy293:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy308;
	default:	goto yy235;
	}
yy294:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy309;
	default:	goto yy235;
	}
yy295:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy310;
	default:	goto yy235;
	}
yy296:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy311;
	default:	goto yy235;
	}
yy297:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy312;
	default:	goto yy235;
	}
yy298:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy313;
	default:	goto yy235;
	}
yy299:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy299;
	case '(':	goto yy301;
	default:	goto yy235;
	}
yy301:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy301;
	default:	goto yy303;
	}
yy303:
	a = yyt1;
	b = yyt2;
	state = yychandle;
	{
            copy_string(buffers[0], a, b);
            callbacks->begin_handle(context, buffers[0]);
            continue;
        }
yy304:
	++s;
	a = yyt1;
	b = s - 1;
	{
            copy_string(buffers[0], a, b);
            callbacks->begin_handle(context, buffers[0]);
            callbacks->end_handle(context);
            continue;
        }
yy306:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt8 = s;
		goto yy314;
	case ')':
		yyt8 = s;
		goto yy316;
	default:	goto yy315;
	}
yy307:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy320;
	default:	goto yy235;
	}
yy308:
	yych = *++s;
	switch (yych) {
	case 'y':	goto yy321;
	default:	goto yy235;
	}
yy309:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy322;
	default:	goto yy235;
	}
yy310:
	yych = *++s;
	switch (yych) {
	case 'm':	goto yy323;
	default:	goto yy235;
	}
yy311:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy324;
	default:	goto yy235;
	}
yy312:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy325;
	default:	goto yy235;
	}
yy313:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy326;
	default:	goto yy235;
	}
yy314:
	yych = *++s;
yy315:
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy314;
	case ')':	goto yy316;
	case ',':	goto yy318;
	default:	goto yy235;
	}
yy316:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy316;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt2 = s;
		goto yy327;
	default:	goto yy235;
	}
yy318:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy318;
	case 'w':	goto yy329;
	default:	goto yy235;
	}
yy320:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt8 = s;
		goto yy330;
	case ')':
		yyt8 = s;
		goto yy316;
	default:	goto yy235;
	}
yy321:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt4 = s;
		goto yy332;
	case '=':
		yyt4 = s;
		goto yy334;
	default:	goto yy235;
	}
yy322:
	yych = *++s;
	switch (yych) {
	case 'l':	goto yy321;
	default:	goto yy235;
	}
yy323:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy336;
	default:	goto yy235;
	}
yy324:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy337;
	default:	goto yy235;
	}
yy325:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy338;
	default:	goto yy235;
	}
yy326:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy321;
	default:	goto yy235;
	}
yy327:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt3 = s;
		goto yy339;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy327;
	case ':':
		yyt3 = s;
		goto yy341;
	default:	goto yy235;
	}
yy329:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy343;
	default:	goto yy235;
	}
yy330:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy330;
	case ')':	goto yy316;
	default:	goto yy235;
	}
yy332:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy332;
	case '=':	goto yy334;
	default:	goto yy235;
	}
yy334:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy334;
	case '"':
		yyt5 = s;
		goto yy344;
	case '-':
		yyt5 = s;
		goto yy346;
	case '0':
		yyt5 = s;
		goto yy347;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt5 = s;
		goto yy348;
	default:	goto yy235;
	}
yy336:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy350;
	default:	goto yy235;
	}
yy337:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy351;
	default:	goto yy235;
	}
yy338:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy352;
	default:	goto yy235;
	}
yy339:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy339;
	case ':':	goto yy341;
	default:	goto yy235;
	}
yy341:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy341;
	case 'a':
		yyt4 = s;
		goto yy353;
	case 'b':
		yyt4 = s;
		goto yy354;
	case 'n':
		yyt4 = s;
		goto yy355;
	case 'o':
		yyt4 = s;
		goto yy356;
	case 's':
		yyt4 = s;
		goto yy357;
	case 'v':
		yyt4 = s;
		goto yy358;
	default:	goto yy235;
	}
yy343:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy359;
	default:	goto yy235;
	}
yy344:
	yych = *++s;
	switch (yych) {
	case 0x00:	goto yy235;
	case '"':	goto yy360;
	default:	goto yy344;
	}
yy346:
	yych = *++s;
	switch (yych) {
	case '0':	goto yy347;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy348;
	default:	goto yy235;
	}
yy347:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt6 = s;
		goto yy361;
	case ';':
		yyt6 = s;
		goto yy363;
	case 'x':	goto yy365;
	default:	goto yy235;
	}
yy348:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt6 = s;
		goto yy361;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy348;
	case ';':
		yyt6 = s;
		goto yy363;
	default:	goto yy235;
	}
yy350:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy321;
	default:	goto yy235;
	}
yy351:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy321;
	default:	goto yy235;
	}
yy352:
	yych = *++s;
	switch (yych) {
	case 'g':	goto yy321;
	default:	goto yy235;
	}
yy353:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy366;
	default:	goto yy235;
	}
yy354:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy367;
	default:	goto yy235;
	}
yy355:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy368;
	default:	goto yy235;
	}
yy356:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy369;
	default:	goto yy235;
	}
yy357:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy370;
	default:	goto yy235;
	}
yy358:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy371;
	default:	goto yy235;
	}
yy359:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy372;
	default:	goto yy235;
	}
yy360:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt6 = s;
		goto yy361;
	case ';':
		yyt6 = s;
		goto yy363;
	default:	goto yy235;
	}
yy361:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy361;
	case ';':	goto yy363;
	default:	goto yy235;
	}
yy363:
	++s;
	a = yyt1;
	b = yyt2;
	c = yyt3;
	d = yyt4;
	e = yyt5;
	f = yyt6;
	{
            copy_string(buffers[2], e, f);
            if (buffers[2][0] == '"') {
                if (!callbacks->constant_string(context, copy_string(buffers[0], a, b), copy_string(buffers[1], c, d), buffers[2])) {
                    return false;
                }
            } else if (isdigit(buffers[2][0])) {
                if (buffers[2][1] == 'x') {
                    callbacks->constant_number(context, copy_string(buffers[0], a, b), copy_string(buffers[1], c, d), strtol(buffers[2]+2, NULL, 16));
                } else {
                    callbacks->constant_number(context, copy_string(buffers[0], a, b), copy_string(buffers[1], c, d), strtol(buffers[2], NULL, 10));
                }
            }
            continue;
        }
yy365:
	yych = *++s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy373;
	default:	goto yy235;
	}
yy366:
	yych = *++s;
	switch (yych) {
	case 'y':	goto yy375;
	default:	goto yy235;
	}
yy367:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy376;
	default:	goto yy235;
	}
yy368:
	yych = *++s;
	switch (yych) {
	case 'm':	goto yy377;
	default:	goto yy235;
	}
yy369:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy378;
	default:	goto yy235;
	}
yy370:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy379;
	default:	goto yy235;
	}
yy371:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy380;
	default:	goto yy235;
	}
yy372:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy381;
	default:	goto yy235;
	}
yy373:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt6 = s;
		goto yy361;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy373;
	case ';':
		yyt6 = s;
		goto yy363;
	default:	goto yy235;
	}
yy375:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt5 = s;
		goto yy383;
	case '=':
		yyt5 = s;
		goto yy385;
	default:	goto yy235;
	}
yy376:
	yych = *++s;
	switch (yych) {
	case 'l':	goto yy375;
	default:	goto yy235;
	}
yy377:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy387;
	default:	goto yy235;
	}
yy378:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy388;
	default:	goto yy235;
	}
yy379:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy389;
	default:	goto yy235;
	}
yy380:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy375;
	default:	goto yy235;
	}
yy381:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy381;
	case ')':	goto yy390;
	default:	goto yy235;
	}
yy383:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy383;
	case '=':	goto yy385;
	default:	goto yy235;
	}
yy385:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy385;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt6 = s;
		goto yy392;
	default:	goto yy235;
	}
yy387:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy394;
	default:	goto yy235;
	}
yy388:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy395;
	default:	goto yy235;
	}
yy389:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy396;
	default:	goto yy235;
	}
yy390:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy390;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy397;
	default:	goto yy235;
	}
yy392:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt7 = s;
		goto yy399;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy392;
	case ';':
		yyt7 = s;
		goto yy401;
	default:	goto yy235;
	}
yy394:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy375;
	default:	goto yy235;
	}
yy395:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy375;
	default:	goto yy235;
	}
yy396:
	yych = *++s;
	switch (yych) {
	case 'g':	goto yy375;
	default:	goto yy235;
	}
yy397:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy403;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy397;
	case ':':
		yyt2 = s;
		goto yy405;
	default:	goto yy235;
	}
yy399:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy399;
	case ';':	goto yy401;
	default:	goto yy235;
	}
yy401:
	++s;
	a = yyt1;
	b = yyt8;
	c = yyt2;
	d = yyt3;
	e = yyt4;
	f = yyt5;
	g = yyt6;
	h = yyt7;
	{
            callbacks->property(
                context,
                copy_string(buffers[0], c, d), // name
                copy_string(buffers[1], e, f), // type
                copy_string(buffers[2], a, b), // mode
                copy_string(buffers[3], g, h),
                NULL
            );
            continue;
        }
yy403:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy403;
	case ':':	goto yy405;
	default:	goto yy235;
	}
yy405:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy405;
	case 'a':
		yyt3 = s;
		goto yy407;
	case 'b':
		yyt3 = s;
		goto yy408;
	case 'n':
		yyt3 = s;
		goto yy409;
	case 'o':
		yyt3 = s;
		goto yy410;
	case 's':
		yyt3 = s;
		goto yy411;
	case 'v':
		yyt3 = s;
		goto yy412;
	default:	goto yy235;
	}
yy407:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy413;
	default:	goto yy235;
	}
yy408:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy414;
	default:	goto yy235;
	}
yy409:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy415;
	default:	goto yy235;
	}
yy410:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy416;
	default:	goto yy235;
	}
yy411:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy417;
	default:	goto yy235;
	}
yy412:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy418;
	default:	goto yy235;
	}
yy413:
	yych = *++s;
	switch (yych) {
	case 'y':	goto yy419;
	default:	goto yy235;
	}
yy414:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy420;
	default:	goto yy235;
	}
yy415:
	yych = *++s;
	switch (yych) {
	case 'm':	goto yy421;
	default:	goto yy235;
	}
yy416:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy422;
	default:	goto yy235;
	}
yy417:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy423;
	default:	goto yy235;
	}
yy418:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy424;
	default:	goto yy235;
	}
yy419:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt4 = s;
		goto yy425;
	case '=':
		yyt4 = s;
		goto yy427;
	default:	goto yy235;
	}
yy420:
	yych = *++s;
	switch (yych) {
	case 'l':	goto yy419;
	default:	goto yy235;
	}
yy421:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy429;
	default:	goto yy235;
	}
yy422:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy430;
	default:	goto yy235;
	}
yy423:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy431;
	default:	goto yy235;
	}
yy424:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy419;
	default:	goto yy235;
	}
yy425:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy425;
	case '=':	goto yy427;
	default:	goto yy235;
	}
yy427:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy427;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt5 = s;
		goto yy432;
	default:	goto yy235;
	}
yy429:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy434;
	default:	goto yy235;
	}
yy430:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy435;
	default:	goto yy235;
	}
yy431:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy436;
	default:	goto yy235;
	}
yy432:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt6 = s;
		goto yy437;
	case ',':
		yyt6 = s;
		goto yy439;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy432;
	default:	goto yy235;
	}
yy434:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy419;
	default:	goto yy235;
	}
yy435:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy419;
	default:	goto yy235;
	}
yy436:
	yych = *++s;
	switch (yych) {
	case 'g':	goto yy419;
	default:	goto yy235;
	}
yy437:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy437;
	case ',':	goto yy439;
	default:	goto yy235;
	}
yy439:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy439;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt7 = s;
		goto yy441;
	default:	goto yy235;
	}
yy441:
	yych = *++s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy441;
	case ';':
		yyt8 = s;
		goto yy443;
	default:	goto yy235;
	}
yy443:
	++s;
	a = yyt1;
	b = yyt2;
	c = yyt3;
	d = yyt4;
	e = yyt5;
	f = yyt6;
	g = yyt7;
	ws = yyt8;
	h = s - 1;
	{
            callbacks->property(
                context,
                copy_string(buffers[0], a, b),  // name
                copy_string(buffers[1], c, d), // type
                "read,write", // mode
                copy_string(buffers[2], e, f), // symbol1
                copy_string(buffers[3], g, h) // symbol2
            );
            continue;
        }
/* *********************************** */
yyc_object:
	yych = *s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy449;
	case '#':	goto yy452;
	case 'p':	goto yy453;
	case '}':	goto yy454;
	default:	goto yy447;
	}
yy447:
	++s;
yy448:
	{ callbacks->error(context, start, s - start); return false; }
yy449:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy449;
	default:	goto yy451;
	}
yy451:
	{ continue; }
yy452:
	yych = *(YYMARKER = ++s);
	if (yych <= 0x00) goto yy448;
	goto yy457;
yy453:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'r':	goto yy461;
	default:	goto yy448;
	}
yy454:
	++s;
	state = yycmodule;
	{ callbacks->end_object(context); continue; }
yy456:
	yych = *++s;
yy457:
	switch (yych) {
	case 0x00:	goto yy458;
	case '\n':	goto yy459;
	default:	goto yy456;
	}
yy458:
	s = YYMARKER;
	goto yy448;
yy459:
	++s;
	{ /* comment */ continue; }
yy461:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy462;
	default:	goto yy458;
	}
yy462:
	yych = *++s;
	switch (yych) {
	case 'p':	goto yy463;
	default:	goto yy458;
	}
yy463:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy463;
	case '(':	goto yy465;
	default:	goto yy458;
	}
yy465:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy465;
	case 'r':
		yyt1 = s;
		goto yy467;
	case 'w':
		yyt1 = s;
		goto yy468;
	default:	goto yy458;
	}
yy467:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy469;
	default:	goto yy458;
	}
yy468:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy470;
	default:	goto yy458;
	}
yy469:
	yych = *++s;
	switch (yych) {
	case 'a':	goto yy471;
	default:	goto yy458;
	}
yy470:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy472;
	default:	goto yy458;
	}
yy471:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy473;
	default:	goto yy458;
	}
yy472:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy474;
	default:	goto yy458;
	}
yy473:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt8 = s;
		goto yy475;
	case ')':
		yyt8 = s;
		goto yy477;
	default:	goto yy476;
	}
yy474:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy481;
	default:	goto yy458;
	}
yy475:
	yych = *++s;
yy476:
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy475;
	case ')':	goto yy477;
	case ',':	goto yy479;
	default:	goto yy458;
	}
yy477:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy477;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt2 = s;
		goto yy482;
	default:	goto yy458;
	}
yy479:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy479;
	case 'w':	goto yy484;
	default:	goto yy458;
	}
yy481:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt8 = s;
		goto yy485;
	case ')':
		yyt8 = s;
		goto yy477;
	default:	goto yy458;
	}
yy482:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt3 = s;
		goto yy487;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy482;
	case ':':
		yyt3 = s;
		goto yy489;
	default:	goto yy458;
	}
yy484:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy491;
	default:	goto yy458;
	}
yy485:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy485;
	case ')':	goto yy477;
	default:	goto yy458;
	}
yy487:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy487;
	case ':':	goto yy489;
	default:	goto yy458;
	}
yy489:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy489;
	case 'a':
		yyt4 = s;
		goto yy492;
	case 'b':
		yyt4 = s;
		goto yy493;
	case 'n':
		yyt4 = s;
		goto yy494;
	case 'o':
		yyt4 = s;
		goto yy495;
	case 's':
		yyt4 = s;
		goto yy496;
	case 'v':
		yyt4 = s;
		goto yy497;
	default:	goto yy458;
	}
yy491:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy498;
	default:	goto yy458;
	}
yy492:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy499;
	default:	goto yy458;
	}
yy493:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy500;
	default:	goto yy458;
	}
yy494:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy501;
	default:	goto yy458;
	}
yy495:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy502;
	default:	goto yy458;
	}
yy496:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy503;
	default:	goto yy458;
	}
yy497:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy504;
	default:	goto yy458;
	}
yy498:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy505;
	default:	goto yy458;
	}
yy499:
	yych = *++s;
	switch (yych) {
	case 'y':	goto yy506;
	default:	goto yy458;
	}
yy500:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy507;
	default:	goto yy458;
	}
yy501:
	yych = *++s;
	switch (yych) {
	case 'm':	goto yy508;
	default:	goto yy458;
	}
yy502:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy509;
	default:	goto yy458;
	}
yy503:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy510;
	default:	goto yy458;
	}
yy504:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy511;
	default:	goto yy458;
	}
yy505:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy512;
	default:	goto yy458;
	}
yy506:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt5 = s;
		goto yy514;
	case '=':
		yyt5 = s;
		goto yy516;
	default:	goto yy458;
	}
yy507:
	yych = *++s;
	switch (yych) {
	case 'l':	goto yy506;
	default:	goto yy458;
	}
yy508:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy518;
	default:	goto yy458;
	}
yy509:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy519;
	default:	goto yy458;
	}
yy510:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy520;
	default:	goto yy458;
	}
yy511:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy506;
	default:	goto yy458;
	}
yy512:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy512;
	case ')':	goto yy521;
	default:	goto yy458;
	}
yy514:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy514;
	case '=':	goto yy516;
	default:	goto yy458;
	}
yy516:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy516;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt6 = s;
		goto yy523;
	default:	goto yy458;
	}
yy518:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy525;
	default:	goto yy458;
	}
yy519:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy526;
	default:	goto yy458;
	}
yy520:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy527;
	default:	goto yy458;
	}
yy521:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy521;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy528;
	default:	goto yy458;
	}
yy523:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt7 = s;
		goto yy530;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy523;
	case ';':
		yyt7 = s;
		goto yy532;
	default:	goto yy458;
	}
yy525:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy506;
	default:	goto yy458;
	}
yy526:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy506;
	default:	goto yy458;
	}
yy527:
	yych = *++s;
	switch (yych) {
	case 'g':	goto yy506;
	default:	goto yy458;
	}
yy528:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy534;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy528;
	case ':':
		yyt2 = s;
		goto yy536;
	default:	goto yy458;
	}
yy530:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy530;
	case ';':	goto yy532;
	default:	goto yy458;
	}
yy532:
	++s;
	a = yyt1;
	b = yyt8;
	c = yyt2;
	d = yyt3;
	e = yyt4;
	f = yyt5;
	g = yyt6;
	h = yyt7;
	{
            callbacks->property(
                context,
                copy_string(buffers[0], c, d), // name
                copy_string(buffers[1], e, f), // type
                copy_string(buffers[2], a, b), // mode
                copy_string(buffers[3], g, h),
                NULL
            );
            continue;
        }
yy534:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy534;
	case ':':	goto yy536;
	default:	goto yy458;
	}
yy536:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy536;
	case 'a':
		yyt3 = s;
		goto yy538;
	case 'b':
		yyt3 = s;
		goto yy539;
	case 'n':
		yyt3 = s;
		goto yy540;
	case 'o':
		yyt3 = s;
		goto yy541;
	case 's':
		yyt3 = s;
		goto yy542;
	case 'v':
		yyt3 = s;
		goto yy543;
	default:	goto yy458;
	}
yy538:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy544;
	default:	goto yy458;
	}
yy539:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy545;
	default:	goto yy458;
	}
yy540:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy546;
	default:	goto yy458;
	}
yy541:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy547;
	default:	goto yy458;
	}
yy542:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy548;
	default:	goto yy458;
	}
yy543:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy549;
	default:	goto yy458;
	}
yy544:
	yych = *++s;
	switch (yych) {
	case 'y':	goto yy550;
	default:	goto yy458;
	}
yy545:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy551;
	default:	goto yy458;
	}
yy546:
	yych = *++s;
	switch (yych) {
	case 'm':	goto yy552;
	default:	goto yy458;
	}
yy547:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy553;
	default:	goto yy458;
	}
yy548:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy554;
	default:	goto yy458;
	}
yy549:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy555;
	default:	goto yy458;
	}
yy550:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt4 = s;
		goto yy556;
	case '=':
		yyt4 = s;
		goto yy558;
	default:	goto yy458;
	}
yy551:
	yych = *++s;
	switch (yych) {
	case 'l':	goto yy550;
	default:	goto yy458;
	}
yy552:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy560;
	default:	goto yy458;
	}
yy553:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy561;
	default:	goto yy458;
	}
yy554:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy562;
	default:	goto yy458;
	}
yy555:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy550;
	default:	goto yy458;
	}
yy556:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy556;
	case '=':	goto yy558;
	default:	goto yy458;
	}
yy558:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy558;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt5 = s;
		goto yy563;
	default:	goto yy458;
	}
yy560:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy565;
	default:	goto yy458;
	}
yy561:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy566;
	default:	goto yy458;
	}
yy562:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy567;
	default:	goto yy458;
	}
yy563:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt6 = s;
		goto yy568;
	case ',':
		yyt6 = s;
		goto yy570;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy563;
	default:	goto yy458;
	}
yy565:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy550;
	default:	goto yy458;
	}
yy566:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy550;
	default:	goto yy458;
	}
yy567:
	yych = *++s;
	switch (yych) {
	case 'g':	goto yy550;
	default:	goto yy458;
	}
yy568:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy568;
	case ',':	goto yy570;
	default:	goto yy458;
	}
yy570:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy570;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt7 = s;
		goto yy572;
	default:	goto yy458;
	}
yy572:
	yych = *++s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy572;
	case ';':
		yyt8 = s;
		goto yy574;
	default:	goto yy458;
	}
yy574:
	++s;
	a = yyt1;
	b = yyt2;
	c = yyt3;
	d = yyt4;
	e = yyt5;
	f = yyt6;
	g = yyt7;
	ws = yyt8;
	h = s - 1;
	{
            callbacks->property(
                context,
                copy_string(buffers[0], a, b),  // name
                copy_string(buffers[1], c, d), // type
                "read,write", // mode
                copy_string(buffers[2], e, f), // symbol1
                copy_string(buffers[3], g, h) // symbol2
            );
            continue;
        }
}

    }
}
