/* Generated by re2c 2.1.1 on Sat Jun  5 13:25:05 2021 */
#include <stdbool.h>
#include <memory.h>
#include <ctype.h>
#include "kalos_idl_parse.h"
#include "kalos_module.h"

// Comparison equivalent to 'unsigned == 0'
#pragma warning 136 9

enum yyc_state {
    yycinit,
    yycmodule,
    yycfunction,
    yycfcomma,
    yycfret,
    yychandle,
    yychcomma,
    yycobject,
};

const char* copy_string(char* buffer, const char* a, const char* b) {
    memcpy(buffer, a, b-a);
    buffer[b-a] = 0;
    return (const char*)buffer;
}

bool kalos_idl_parse_callback(const char* s, void* context, kalos_idl_callbacks* callbacks) {
    const char* start = s;
    const char* YYMARKER;
    const char *ws, *a, *b, *c, *d, *e, *f, *g, *h;
    enum yyc_state state = yycinit;

    char buffers[4][128];

    const char *yyt1; const char *yyt2; const char *yyt3; const char *yyt4; const char *yyt5; const char *yyt6; const char *yyt7; const char *yyt8; 

    for (;;) {
    
{
	char yych;
	unsigned int yyaccept = 0;
	switch (state) {
	case yycfcomma:
		goto yyc_fcomma;
	case yycfret:
		goto yyc_fret;
	case yycfunction:
		goto yyc_function;
	case yychandle:
		goto yyc_handle;
	case yychcomma:
		goto yyc_hcomma;
	case yycinit:
		goto yyc_init;
	case yycmodule:
		goto yyc_module;
	case yycobject:
		goto yyc_object;
	}
/* *********************************** */
yyc_fcomma:
	yych = *s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy4;
	case ')':	goto yy7;
	case ',':	goto yy9;
	default:	goto yy2;
	}
yy2:
	++s;
	{ callbacks->error(context, start, s - start); return false; }
yy4:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy4;
	default:	goto yy6;
	}
yy6:
	{ continue; }
yy7:
	++s;
	state = yycfret;
	goto yyc_fret;
yy9:
	++s;
	state = yycfunction;
	goto yyc_function;
/* *********************************** */
yyc_fret:
	yych = *s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt3 = yyt4 = NULL;
		goto yy15;
	case ':':	goto yy18;
	case '=':
		yyt3 = yyt4 = NULL;
		goto yy19;
	default:	goto yy13;
	}
yy13:
	++s;
yy14:
	{ callbacks->error(context, start, s - start); return false; }
yy15:
	yyaccept = 0;
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy15;
	case '=':	goto yy20;
	default:	goto yy17;
	}
yy17:
	{ continue; }
yy18:
	yyaccept = 1;
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case 'a':
	case 'n':
	case 'o':
	case 's':
	case 'v':	goto yy24;
	default:	goto yy14;
	}
yy19:
	yyaccept = 1;
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy20;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy30;
	default:	goto yy14;
	}
yy20:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy20;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy30;
	default:	goto yy22;
	}
yy22:
	s = YYMARKER;
	if (yyaccept == 0) {
		goto yy17;
	} else {
		goto yy14;
	}
yy23:
	yych = *++s;
yy24:
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy23;
	case 'a':
		yyt3 = s;
		goto yy25;
	case 'n':
		yyt3 = s;
		goto yy26;
	case 'o':
		yyt3 = s;
		goto yy27;
	case 's':
		yyt3 = s;
		goto yy28;
	case 'v':
		yyt3 = s;
		goto yy29;
	default:	goto yy22;
	}
yy25:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy32;
	default:	goto yy22;
	}
yy26:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy33;
	default:	goto yy22;
	}
yy27:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy34;
	default:	goto yy22;
	}
yy28:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy35;
	default:	goto yy22;
	}
yy29:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy36;
	default:	goto yy22;
	}
yy30:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy37;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy30;
	case ';':
		yyt2 = s;
		goto yy39;
	default:	goto yy22;
	}
yy32:
	yych = *++s;
	switch (yych) {
	case 'y':	goto yy41;
	default:	goto yy22;
	}
yy33:
	yych = *++s;
	switch (yych) {
	case 'm':	goto yy42;
	default:	goto yy22;
	}
yy34:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy43;
	default:	goto yy22;
	}
yy35:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy44;
	default:	goto yy22;
	}
yy36:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy45;
	default:	goto yy22;
	}
yy37:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy37;
	case ';':	goto yy39;
	default:	goto yy22;
	}
yy39:
	++s;
	a = yyt3;
	b = yyt4;
	c = yyt1;
	d = yyt2;
	state = yycmodule;
	{
            if (a && b) {
                copy_string(buffers[1], a, b);
            } else {
                strcpy(buffers[1], "void");
            }
            callbacks->end_function(context, buffers[0], buffers[1], copy_string(buffers[2], c, d));
            continue;
        }
yy41:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt4 = s;
		goto yy46;
	case '=':
		yyt4 = s;
		goto yy20;
	default:	goto yy22;
	}
yy42:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy48;
	default:	goto yy22;
	}
yy43:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy49;
	default:	goto yy22;
	}
yy44:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy50;
	default:	goto yy22;
	}
yy45:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy41;
	default:	goto yy22;
	}
yy46:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy46;
	case '=':	goto yy20;
	default:	goto yy22;
	}
yy48:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy51;
	default:	goto yy22;
	}
yy49:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy52;
	default:	goto yy22;
	}
yy50:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy53;
	default:	goto yy22;
	}
yy51:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy41;
	default:	goto yy22;
	}
yy52:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy41;
	default:	goto yy22;
	}
yy53:
	yych = *++s;
	switch (yych) {
	case 'g':	goto yy41;
	default:	goto yy22;
	}
/* *********************************** */
yyc_function:
	yych = *s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy58;
	case ')':	goto yy61;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy63;
	default:	goto yy56;
	}
yy56:
	++s;
yy57:
	{ callbacks->error(context, start, s - start); return false; }
yy58:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy58;
	default:	goto yy60;
	}
yy60:
	{ continue; }
yy61:
	++s;
	state = yycfret;
	goto yyc_fret;
yy63:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy68;
	default:	goto yy57;
	}
yy64:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy64;
	case ':':	goto yy69;
	default:	goto yy66;
	}
yy66:
	s = YYMARKER;
	goto yy57;
yy67:
	yych = *++s;
yy68:
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy64;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy67;
	case ':':
		yyt2 = s;
		goto yy69;
	default:	goto yy66;
	}
yy69:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy69;
	case 'a':
		yyt3 = s;
		goto yy71;
	case 'n':
		yyt3 = s;
		goto yy72;
	case 'o':
		yyt3 = s;
		goto yy73;
	case 's':
		yyt3 = s;
		goto yy74;
	case 'v':
		yyt3 = s;
		goto yy75;
	default:	goto yy66;
	}
yy71:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy76;
	default:	goto yy66;
	}
yy72:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy77;
	default:	goto yy66;
	}
yy73:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy78;
	default:	goto yy66;
	}
yy74:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy79;
	default:	goto yy66;
	}
yy75:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy80;
	default:	goto yy66;
	}
yy76:
	yych = *++s;
	switch (yych) {
	case 'y':	goto yy81;
	default:	goto yy66;
	}
yy77:
	yych = *++s;
	switch (yych) {
	case 'm':	goto yy82;
	default:	goto yy66;
	}
yy78:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy83;
	default:	goto yy66;
	}
yy79:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy84;
	default:	goto yy66;
	}
yy80:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy85;
	default:	goto yy66;
	}
yy81:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt4 = s;
		goto yy86;
	case ')':
	case ',':
		yyt5 = NULL;
		yyt4 = s;
		goto yy88;
	case '.':
		yyt4 = s;
		goto yy90;
	default:	goto yy66;
	}
yy82:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy91;
	default:	goto yy66;
	}
yy83:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy92;
	default:	goto yy66;
	}
yy84:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy93;
	default:	goto yy66;
	}
yy85:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy81;
	default:	goto yy66;
	}
yy86:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy86;
	case ')':
	case ',':
		yyt5 = NULL;
		goto yy88;
	case '.':	goto yy90;
	default:	goto yy66;
	}
yy88:
	++s;
	a = yyt1;
	b = yyt2;
	c = yyt3;
	d = yyt4;
	f = yyt5;
	s -= 1;
	e = yyt5;
	if (yyt5 != NULL) e -= 3;
	state = yycfcomma;
	{
            callbacks->function_arg(context, copy_string(buffers[1], a, b), copy_string(buffers[2], c, d), e != NULL);
            continue;
        }
yy90:
	yych = *++s;
	switch (yych) {
	case '.':	goto yy94;
	default:	goto yy66;
	}
yy91:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy95;
	default:	goto yy66;
	}
yy92:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy96;
	default:	goto yy66;
	}
yy93:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy97;
	default:	goto yy66;
	}
yy94:
	yych = *++s;
	switch (yych) {
	case '.':	goto yy98;
	default:	goto yy66;
	}
yy95:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy81;
	default:	goto yy66;
	}
yy96:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy81;
	default:	goto yy66;
	}
yy97:
	yych = *++s;
	switch (yych) {
	case 'g':	goto yy81;
	default:	goto yy66;
	}
yy98:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt5 = s;
		goto yy99;
	case ')':
	case ',':
		yyt5 = s;
		goto yy88;
	default:	goto yy66;
	}
yy99:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy99;
	case ')':
	case ',':	goto yy88;
	default:	goto yy66;
	}
/* *********************************** */
yyc_handle:
	yych = *s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy105;
	case ')':	goto yy108;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy109;
	default:	goto yy103;
	}
yy103:
	++s;
yy104:
	{ callbacks->error(context, start, s - start); return false; }
yy105:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy105;
	default:	goto yy107;
	}
yy107:
	{ continue; }
yy108:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy110;
	case ';':	goto yy113;
	default:	goto yy104;
	}
yy109:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy118;
	default:	goto yy104;
	}
yy110:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy110;
	case ';':	goto yy113;
	default:	goto yy112;
	}
yy112:
	s = YYMARKER;
	goto yy104;
yy113:
	++s;
	state = yycmodule;
	{
            callbacks->end_handle(context);
        }
yy115:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy115;
	case ':':	goto yy119;
	default:	goto yy112;
	}
yy117:
	yych = *++s;
yy118:
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy115;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy117;
	case ':':
		yyt2 = s;
		goto yy119;
	default:	goto yy112;
	}
yy119:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy119;
	case 'a':
		yyt3 = s;
		goto yy121;
	case 'n':
		yyt3 = s;
		goto yy122;
	case 'o':
		yyt3 = s;
		goto yy123;
	case 's':
		yyt3 = s;
		goto yy124;
	case 'v':
		yyt3 = s;
		goto yy125;
	default:	goto yy112;
	}
yy121:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy126;
	default:	goto yy112;
	}
yy122:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy127;
	default:	goto yy112;
	}
yy123:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy128;
	default:	goto yy112;
	}
yy124:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy129;
	default:	goto yy112;
	}
yy125:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy130;
	default:	goto yy112;
	}
yy126:
	yych = *++s;
	switch (yych) {
	case 'y':	goto yy131;
	default:	goto yy112;
	}
yy127:
	yych = *++s;
	switch (yych) {
	case 'm':	goto yy132;
	default:	goto yy112;
	}
yy128:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy133;
	default:	goto yy112;
	}
yy129:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy134;
	default:	goto yy112;
	}
yy130:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy135;
	default:	goto yy112;
	}
yy131:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt4 = s;
		goto yy136;
	case ')':
	case ',':
		yyt5 = NULL;
		yyt4 = s;
		goto yy138;
	case '.':
		yyt4 = s;
		goto yy140;
	default:	goto yy112;
	}
yy132:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy141;
	default:	goto yy112;
	}
yy133:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy142;
	default:	goto yy112;
	}
yy134:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy143;
	default:	goto yy112;
	}
yy135:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy131;
	default:	goto yy112;
	}
yy136:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy136;
	case ')':
	case ',':
		yyt5 = NULL;
		goto yy138;
	case '.':	goto yy140;
	default:	goto yy112;
	}
yy138:
	++s;
	a = yyt1;
	b = yyt2;
	c = yyt3;
	d = yyt4;
	f = yyt5;
	s -= 1;
	e = yyt5;
	if (yyt5 != NULL) e -= 3;
	state = yychcomma;
	{
            callbacks->handle_arg(context, copy_string(buffers[1], a, b), copy_string(buffers[2], c, d), e != NULL);
            continue;
        }
yy140:
	yych = *++s;
	switch (yych) {
	case '.':	goto yy144;
	default:	goto yy112;
	}
yy141:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy145;
	default:	goto yy112;
	}
yy142:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy146;
	default:	goto yy112;
	}
yy143:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy147;
	default:	goto yy112;
	}
yy144:
	yych = *++s;
	switch (yych) {
	case '.':	goto yy148;
	default:	goto yy112;
	}
yy145:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy131;
	default:	goto yy112;
	}
yy146:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy131;
	default:	goto yy112;
	}
yy147:
	yych = *++s;
	switch (yych) {
	case 'g':	goto yy131;
	default:	goto yy112;
	}
yy148:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt5 = s;
		goto yy149;
	case ')':
	case ',':
		yyt5 = s;
		goto yy138;
	default:	goto yy112;
	}
yy149:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy149;
	case ')':
	case ',':	goto yy138;
	default:	goto yy112;
	}
/* *********************************** */
yyc_hcomma:
	yych = *s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy155;
	case ')':	goto yy158;
	case ',':	goto yy159;
	default:	goto yy153;
	}
yy153:
	++s;
yy154:
	{ callbacks->error(context, start, s - start); return false; }
yy155:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy155;
	default:	goto yy157;
	}
yy157:
	{ continue; }
yy158:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy161;
	case ';':	goto yy164;
	default:	goto yy154;
	}
yy159:
	++s;
	state = yychandle;
	goto yyc_handle;
yy161:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy161;
	case ';':	goto yy164;
	default:	goto yy163;
	}
yy163:
	s = YYMARKER;
	goto yy154;
yy164:
	++s;
	state = yycmodule;
	{
            callbacks->end_handle(context);
        }
/* *********************************** */
yyc_init:
	yych = *s;
	switch (yych) {
	case 0x00:	goto yy168;
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy172;
	case '#':	goto yy175;
	case 'm':	goto yy176;
	case 'p':	goto yy177;
	default:	goto yy170;
	}
yy168:
	++s;
	{ return true; }
yy170:
	++s;
yy171:
	{ callbacks->error(context, start, s - start); return false; }
yy172:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy172;
	default:	goto yy174;
	}
yy174:
	{ continue; }
yy175:
	yych = *(YYMARKER = ++s);
	if (yych <= 0x00) goto yy171;
	goto yy179;
yy176:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'o':	goto yy183;
	default:	goto yy171;
	}
yy177:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'r':	goto yy184;
	default:	goto yy171;
	}
yy178:
	yych = *++s;
yy179:
	switch (yych) {
	case 0x00:	goto yy180;
	case '\n':	goto yy181;
	default:	goto yy178;
	}
yy180:
	s = YYMARKER;
	goto yy171;
yy181:
	++s;
	{ /* comment */ continue; }
yy183:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy185;
	default:	goto yy180;
	}
yy184:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy186;
	default:	goto yy180;
	}
yy185:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy187;
	default:	goto yy180;
	}
yy186:
	yych = *++s;
	switch (yych) {
	case 'f':	goto yy188;
	default:	goto yy180;
	}
yy187:
	yych = *++s;
	switch (yych) {
	case 'l':	goto yy189;
	default:	goto yy180;
	}
yy188:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy190;
	default:	goto yy180;
	}
yy189:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy191;
	default:	goto yy180;
	}
yy190:
	yych = *++s;
	switch (yych) {
	case 'x':	goto yy192;
	default:	goto yy180;
	}
yy191:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy194;
	default:	goto yy180;
	}
yy192:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy192;
	case '"':
		yyt1 = s;
		goto yy196;
	default:	goto yy180;
	}
yy194:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy194;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy198;
	default:	goto yy180;
	}
yy196:
	yych = *++s;
	switch (yych) {
	case 0x00:	goto yy180;
	case '"':	goto yy200;
	default:	goto yy196;
	}
yy198:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy201;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy198;
	case '{':
		yyt2 = s;
		goto yy203;
	default:	goto yy180;
	}
yy200:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy205;
	case ';':
		yyt2 = s;
		goto yy207;
	default:	goto yy180;
	}
yy201:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy201;
	case '{':	goto yy203;
	default:	goto yy180;
	}
yy203:
	++s;
	a = yyt1;
	b = yyt2;
	state = yycmodule;
	{ callbacks->begin_module(context, copy_string(buffers[0], a, b)); continue; }
yy205:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy205;
	case ';':	goto yy207;
	default:	goto yy180;
	}
yy207:
	++s;
	a = yyt1;
	b = yyt2;
	{ callbacks->prefix(context, copy_string(buffers[0], a, b)); continue; }
/* *********************************** */
yyc_module:
	yych = *s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy213;
	case '#':	goto yy216;
	case 'c':	goto yy217;
	case 'f':	goto yy218;
	case 'h':	goto yy219;
	case 'o':	goto yy220;
	case 'p':	goto yy221;
	case '}':	goto yy222;
	default:	goto yy211;
	}
yy211:
	++s;
yy212:
	{ callbacks->error(context, start, s - start); return false; }
yy213:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy213;
	default:	goto yy215;
	}
yy215:
	{ continue; }
yy216:
	yych = *(YYMARKER = ++s);
	if (yych <= 0x00) goto yy212;
	goto yy225;
yy217:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'o':	goto yy229;
	default:	goto yy212;
	}
yy218:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'n':	goto yy230;
	default:	goto yy212;
	}
yy219:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'a':	goto yy231;
	default:	goto yy212;
	}
yy220:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'b':	goto yy232;
	default:	goto yy212;
	}
yy221:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'r':	goto yy233;
	default:	goto yy212;
	}
yy222:
	++s;
	state = yycinit;
	{ callbacks->end_module(context); continue; }
yy224:
	yych = *++s;
yy225:
	switch (yych) {
	case 0x00:	goto yy226;
	case '\n':	goto yy227;
	default:	goto yy224;
	}
yy226:
	s = YYMARKER;
	goto yy212;
yy227:
	++s;
	{ /* comment */ continue; }
yy229:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy234;
	default:	goto yy226;
	}
yy230:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy235;
	default:	goto yy226;
	}
yy231:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy237;
	default:	goto yy226;
	}
yy232:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy238;
	default:	goto yy226;
	}
yy233:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy239;
	default:	goto yy226;
	}
yy234:
	yych = *++s;
	switch (yych) {
	case 's':	goto yy240;
	default:	goto yy226;
	}
yy235:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy235;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy241;
	default:	goto yy226;
	}
yy237:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy243;
	default:	goto yy226;
	}
yy238:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy244;
	default:	goto yy226;
	}
yy239:
	yych = *++s;
	switch (yych) {
	case 'p':	goto yy245;
	default:	goto yy226;
	}
yy240:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy247;
	default:	goto yy226;
	}
yy241:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy248;
	case '(':
		yyt2 = s;
		goto yy250;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy241;
	default:	goto yy226;
	}
yy243:
	yych = *++s;
	switch (yych) {
	case 'l':	goto yy253;
	default:	goto yy226;
	}
yy244:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy254;
	default:	goto yy226;
	}
yy245:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy245;
	case '(':	goto yy255;
	default:	goto yy226;
	}
yy247:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy257;
	default:	goto yy226;
	}
yy248:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy248;
	case '(':	goto yy250;
	default:	goto yy226;
	}
yy250:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy250;
	default:	goto yy252;
	}
yy252:
	a = yyt1;
	b = yyt2;
	state = yycfunction;
	{
            copy_string(buffers[0], a, b);
            callbacks->begin_function(context, buffers[0]);
            continue;
        }
yy253:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy259;
	default:	goto yy226;
	}
yy254:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy260;
	default:	goto yy226;
	}
yy255:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy255;
	case 'r':
		yyt1 = s;
		goto yy262;
	case 'w':
		yyt1 = s;
		goto yy263;
	default:	goto yy226;
	}
yy257:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy257;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy264;
	default:	goto yy226;
	}
yy259:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy266;
	default:	goto yy226;
	}
yy260:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy260;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy268;
	default:	goto yy226;
	}
yy262:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy270;
	default:	goto yy226;
	}
yy263:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy271;
	default:	goto yy226;
	}
yy264:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy272;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy264;
	case ':':
		yyt2 = s;
		goto yy274;
	default:	goto yy226;
	}
yy266:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy266;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy276;
	default:	goto yy226;
	}
yy268:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy278;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy268;
	case '{':
		yyt2 = s;
		goto yy280;
	default:	goto yy226;
	}
yy270:
	yych = *++s;
	switch (yych) {
	case 'a':	goto yy282;
	default:	goto yy226;
	}
yy271:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy283;
	default:	goto yy226;
	}
yy272:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy272;
	case ':':	goto yy274;
	default:	goto yy226;
	}
yy274:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy274;
	case 'a':
		yyt3 = s;
		goto yy284;
	case 'n':
		yyt3 = s;
		goto yy285;
	case 'o':
		yyt3 = s;
		goto yy286;
	case 's':
		yyt3 = s;
		goto yy287;
	case 'v':
		yyt3 = s;
		goto yy288;
	default:	goto yy226;
	}
yy276:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy289;
	case '(':
		yyt2 = s;
		goto yy291;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy276;
	case ';':	goto yy294;
	default:	goto yy226;
	}
yy278:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy278;
	case '{':	goto yy280;
	default:	goto yy226;
	}
yy280:
	++s;
	a = yyt1;
	b = yyt2;
	state = yycobject;
	{ callbacks->begin_object(context, copy_string(buffers[0], a, b)); continue; }
yy282:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy296;
	default:	goto yy226;
	}
yy283:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy297;
	default:	goto yy226;
	}
yy284:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy298;
	default:	goto yy226;
	}
yy285:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy299;
	default:	goto yy226;
	}
yy286:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy300;
	default:	goto yy226;
	}
yy287:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy301;
	default:	goto yy226;
	}
yy288:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy302;
	default:	goto yy226;
	}
yy289:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy289;
	case '(':	goto yy291;
	default:	goto yy226;
	}
yy291:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy291;
	default:	goto yy293;
	}
yy293:
	a = yyt1;
	b = yyt2;
	state = yychandle;
	{
            copy_string(buffers[0], a, b);
            callbacks->begin_handle(context, buffers[0]);
            continue;
        }
yy294:
	++s;
	a = yyt1;
	b = s - 1;
	{
            copy_string(buffers[0], a, b);
            callbacks->begin_handle(context, buffers[0]);
            callbacks->end_handle(context);
            continue;
        }
yy296:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt8 = s;
		goto yy303;
	case ')':
		yyt8 = s;
		goto yy305;
	default:	goto yy304;
	}
yy297:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy309;
	default:	goto yy226;
	}
yy298:
	yych = *++s;
	switch (yych) {
	case 'y':	goto yy310;
	default:	goto yy226;
	}
yy299:
	yych = *++s;
	switch (yych) {
	case 'm':	goto yy311;
	default:	goto yy226;
	}
yy300:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy312;
	default:	goto yy226;
	}
yy301:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy313;
	default:	goto yy226;
	}
yy302:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy314;
	default:	goto yy226;
	}
yy303:
	yych = *++s;
yy304:
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy303;
	case ')':	goto yy305;
	case ',':	goto yy307;
	default:	goto yy226;
	}
yy305:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy305;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt2 = s;
		goto yy315;
	default:	goto yy226;
	}
yy307:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy307;
	case 'w':	goto yy317;
	default:	goto yy226;
	}
yy309:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt8 = s;
		goto yy318;
	case ')':
		yyt8 = s;
		goto yy305;
	default:	goto yy226;
	}
yy310:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt4 = s;
		goto yy320;
	case '=':
		yyt4 = s;
		goto yy322;
	default:	goto yy226;
	}
yy311:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy324;
	default:	goto yy226;
	}
yy312:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy325;
	default:	goto yy226;
	}
yy313:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy326;
	default:	goto yy226;
	}
yy314:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy310;
	default:	goto yy226;
	}
yy315:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt3 = s;
		goto yy327;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy315;
	case ':':
		yyt3 = s;
		goto yy329;
	default:	goto yy226;
	}
yy317:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy331;
	default:	goto yy226;
	}
yy318:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy318;
	case ')':	goto yy305;
	default:	goto yy226;
	}
yy320:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy320;
	case '=':	goto yy322;
	default:	goto yy226;
	}
yy322:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy322;
	case '"':
		yyt5 = s;
		goto yy332;
	case '-':
		yyt5 = s;
		goto yy334;
	case '0':
		yyt5 = s;
		goto yy335;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt5 = s;
		goto yy336;
	default:	goto yy226;
	}
yy324:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy338;
	default:	goto yy226;
	}
yy325:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy339;
	default:	goto yy226;
	}
yy326:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy340;
	default:	goto yy226;
	}
yy327:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy327;
	case ':':	goto yy329;
	default:	goto yy226;
	}
yy329:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy329;
	case 'a':
		yyt4 = s;
		goto yy341;
	case 'n':
		yyt4 = s;
		goto yy342;
	case 'o':
		yyt4 = s;
		goto yy343;
	case 's':
		yyt4 = s;
		goto yy344;
	case 'v':
		yyt4 = s;
		goto yy345;
	default:	goto yy226;
	}
yy331:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy346;
	default:	goto yy226;
	}
yy332:
	yych = *++s;
	switch (yych) {
	case 0x00:	goto yy226;
	case '"':	goto yy347;
	default:	goto yy332;
	}
yy334:
	yych = *++s;
	switch (yych) {
	case '0':	goto yy335;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy336;
	default:	goto yy226;
	}
yy335:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt6 = s;
		goto yy348;
	case ';':
		yyt6 = s;
		goto yy350;
	case 'x':	goto yy352;
	default:	goto yy226;
	}
yy336:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt6 = s;
		goto yy348;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy336;
	case ';':
		yyt6 = s;
		goto yy350;
	default:	goto yy226;
	}
yy338:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy310;
	default:	goto yy226;
	}
yy339:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy310;
	default:	goto yy226;
	}
yy340:
	yych = *++s;
	switch (yych) {
	case 'g':	goto yy310;
	default:	goto yy226;
	}
yy341:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy353;
	default:	goto yy226;
	}
yy342:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy354;
	default:	goto yy226;
	}
yy343:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy355;
	default:	goto yy226;
	}
yy344:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy356;
	default:	goto yy226;
	}
yy345:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy357;
	default:	goto yy226;
	}
yy346:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy358;
	default:	goto yy226;
	}
yy347:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt6 = s;
		goto yy348;
	case ';':
		yyt6 = s;
		goto yy350;
	default:	goto yy226;
	}
yy348:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy348;
	case ';':	goto yy350;
	default:	goto yy226;
	}
yy350:
	++s;
	a = yyt1;
	b = yyt2;
	c = yyt3;
	d = yyt4;
	e = yyt5;
	f = yyt6;
	{
            copy_string(buffers[2], e, f);
            if (buffers[2][0] == '"') {
                callbacks->constant_string(context, copy_string(buffers[0], a, b), copy_string(buffers[1], c, d), buffers[2]);
            } else if (isdigit(buffers[2][0])) {
                if (buffers[2][1] == 'x') {
                    callbacks->constant_number(context, copy_string(buffers[0], a, b), copy_string(buffers[1], c, d), strtol(buffers[2]+2, NULL, 16));
                } else {
                    callbacks->constant_number(context, copy_string(buffers[0], a, b), copy_string(buffers[1], c, d), strtol(buffers[2], NULL, 10));
                }
            }
            continue;
        }
yy352:
	yych = *++s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy359;
	default:	goto yy226;
	}
yy353:
	yych = *++s;
	switch (yych) {
	case 'y':	goto yy361;
	default:	goto yy226;
	}
yy354:
	yych = *++s;
	switch (yych) {
	case 'm':	goto yy362;
	default:	goto yy226;
	}
yy355:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy363;
	default:	goto yy226;
	}
yy356:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy364;
	default:	goto yy226;
	}
yy357:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy365;
	default:	goto yy226;
	}
yy358:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy366;
	default:	goto yy226;
	}
yy359:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt6 = s;
		goto yy348;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy359;
	case ';':
		yyt6 = s;
		goto yy350;
	default:	goto yy226;
	}
yy361:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt5 = s;
		goto yy368;
	case '=':
		yyt5 = s;
		goto yy370;
	default:	goto yy226;
	}
yy362:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy372;
	default:	goto yy226;
	}
yy363:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy373;
	default:	goto yy226;
	}
yy364:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy374;
	default:	goto yy226;
	}
yy365:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy361;
	default:	goto yy226;
	}
yy366:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy366;
	case ')':	goto yy375;
	default:	goto yy226;
	}
yy368:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy368;
	case '=':	goto yy370;
	default:	goto yy226;
	}
yy370:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy370;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt6 = s;
		goto yy377;
	default:	goto yy226;
	}
yy372:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy379;
	default:	goto yy226;
	}
yy373:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy380;
	default:	goto yy226;
	}
yy374:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy381;
	default:	goto yy226;
	}
yy375:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy375;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy382;
	default:	goto yy226;
	}
yy377:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt7 = s;
		goto yy384;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy377;
	case ';':
		yyt7 = s;
		goto yy386;
	default:	goto yy226;
	}
yy379:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy361;
	default:	goto yy226;
	}
yy380:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy361;
	default:	goto yy226;
	}
yy381:
	yych = *++s;
	switch (yych) {
	case 'g':	goto yy361;
	default:	goto yy226;
	}
yy382:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy388;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy382;
	case ':':
		yyt2 = s;
		goto yy390;
	default:	goto yy226;
	}
yy384:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy384;
	case ';':	goto yy386;
	default:	goto yy226;
	}
yy386:
	++s;
	a = yyt1;
	b = yyt8;
	c = yyt2;
	d = yyt3;
	e = yyt4;
	f = yyt5;
	g = yyt6;
	h = yyt7;
	{
            callbacks->property(
                context,
                copy_string(buffers[0], c, d), // name
                copy_string(buffers[1], e, f), // type
                copy_string(buffers[2], a, b), // mode
                copy_string(buffers[3], g, h),
                NULL
            );
            continue;
        }
yy388:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy388;
	case ':':	goto yy390;
	default:	goto yy226;
	}
yy390:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy390;
	case 'a':
		yyt3 = s;
		goto yy392;
	case 'n':
		yyt3 = s;
		goto yy393;
	case 'o':
		yyt3 = s;
		goto yy394;
	case 's':
		yyt3 = s;
		goto yy395;
	case 'v':
		yyt3 = s;
		goto yy396;
	default:	goto yy226;
	}
yy392:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy397;
	default:	goto yy226;
	}
yy393:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy398;
	default:	goto yy226;
	}
yy394:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy399;
	default:	goto yy226;
	}
yy395:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy400;
	default:	goto yy226;
	}
yy396:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy401;
	default:	goto yy226;
	}
yy397:
	yych = *++s;
	switch (yych) {
	case 'y':	goto yy402;
	default:	goto yy226;
	}
yy398:
	yych = *++s;
	switch (yych) {
	case 'm':	goto yy403;
	default:	goto yy226;
	}
yy399:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy404;
	default:	goto yy226;
	}
yy400:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy405;
	default:	goto yy226;
	}
yy401:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy406;
	default:	goto yy226;
	}
yy402:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt4 = s;
		goto yy407;
	case '=':
		yyt4 = s;
		goto yy409;
	default:	goto yy226;
	}
yy403:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy411;
	default:	goto yy226;
	}
yy404:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy412;
	default:	goto yy226;
	}
yy405:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy413;
	default:	goto yy226;
	}
yy406:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy402;
	default:	goto yy226;
	}
yy407:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy407;
	case '=':	goto yy409;
	default:	goto yy226;
	}
yy409:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy409;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt5 = s;
		goto yy414;
	default:	goto yy226;
	}
yy411:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy416;
	default:	goto yy226;
	}
yy412:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy417;
	default:	goto yy226;
	}
yy413:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy418;
	default:	goto yy226;
	}
yy414:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt6 = s;
		goto yy419;
	case ',':
		yyt6 = s;
		goto yy421;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy414;
	default:	goto yy226;
	}
yy416:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy402;
	default:	goto yy226;
	}
yy417:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy402;
	default:	goto yy226;
	}
yy418:
	yych = *++s;
	switch (yych) {
	case 'g':	goto yy402;
	default:	goto yy226;
	}
yy419:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy419;
	case ',':	goto yy421;
	default:	goto yy226;
	}
yy421:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy421;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt7 = s;
		goto yy423;
	default:	goto yy226;
	}
yy423:
	yych = *++s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy423;
	case ';':
		yyt8 = s;
		goto yy425;
	default:	goto yy226;
	}
yy425:
	++s;
	a = yyt1;
	b = yyt2;
	c = yyt3;
	d = yyt4;
	e = yyt5;
	f = yyt6;
	g = yyt7;
	ws = yyt8;
	h = s - 1;
	{
            callbacks->property(
                context,
                copy_string(buffers[0], a, b),  // name
                copy_string(buffers[1], c, d), // type
                "read,write", // mode
                copy_string(buffers[2], e, f), // symbol1
                copy_string(buffers[3], g, h) // symbol2
            );
            continue;
        }
/* *********************************** */
yyc_object:
	yych = *s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy431;
	case '#':	goto yy434;
	case 'p':	goto yy435;
	case '}':	goto yy436;
	default:	goto yy429;
	}
yy429:
	++s;
yy430:
	{ callbacks->error(context, start, s - start); return false; }
yy431:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy431;
	default:	goto yy433;
	}
yy433:
	{ continue; }
yy434:
	yych = *(YYMARKER = ++s);
	if (yych <= 0x00) goto yy430;
	goto yy439;
yy435:
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'r':	goto yy443;
	default:	goto yy430;
	}
yy436:
	++s;
	state = yycmodule;
	{ callbacks->end_object(context); continue; }
yy438:
	yych = *++s;
yy439:
	switch (yych) {
	case 0x00:	goto yy440;
	case '\n':	goto yy441;
	default:	goto yy438;
	}
yy440:
	s = YYMARKER;
	goto yy430;
yy441:
	++s;
	{ /* comment */ continue; }
yy443:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy444;
	default:	goto yy440;
	}
yy444:
	yych = *++s;
	switch (yych) {
	case 'p':	goto yy445;
	default:	goto yy440;
	}
yy445:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy445;
	case '(':	goto yy447;
	default:	goto yy440;
	}
yy447:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy447;
	case 'r':
		yyt1 = s;
		goto yy449;
	case 'w':
		yyt1 = s;
		goto yy450;
	default:	goto yy440;
	}
yy449:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy451;
	default:	goto yy440;
	}
yy450:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy452;
	default:	goto yy440;
	}
yy451:
	yych = *++s;
	switch (yych) {
	case 'a':	goto yy453;
	default:	goto yy440;
	}
yy452:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy454;
	default:	goto yy440;
	}
yy453:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy455;
	default:	goto yy440;
	}
yy454:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy456;
	default:	goto yy440;
	}
yy455:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt8 = s;
		goto yy457;
	case ')':
		yyt8 = s;
		goto yy459;
	default:	goto yy458;
	}
yy456:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy463;
	default:	goto yy440;
	}
yy457:
	yych = *++s;
yy458:
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy457;
	case ')':	goto yy459;
	case ',':	goto yy461;
	default:	goto yy440;
	}
yy459:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy459;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt2 = s;
		goto yy464;
	default:	goto yy440;
	}
yy461:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy461;
	case 'w':	goto yy466;
	default:	goto yy440;
	}
yy463:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt8 = s;
		goto yy467;
	case ')':
		yyt8 = s;
		goto yy459;
	default:	goto yy440;
	}
yy464:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt3 = s;
		goto yy469;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy464;
	case ':':
		yyt3 = s;
		goto yy471;
	default:	goto yy440;
	}
yy466:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy473;
	default:	goto yy440;
	}
yy467:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy467;
	case ')':	goto yy459;
	default:	goto yy440;
	}
yy469:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy469;
	case ':':	goto yy471;
	default:	goto yy440;
	}
yy471:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy471;
	case 'a':
		yyt4 = s;
		goto yy474;
	case 'n':
		yyt4 = s;
		goto yy475;
	case 'o':
		yyt4 = s;
		goto yy476;
	case 's':
		yyt4 = s;
		goto yy477;
	case 'v':
		yyt4 = s;
		goto yy478;
	default:	goto yy440;
	}
yy473:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy479;
	default:	goto yy440;
	}
yy474:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy480;
	default:	goto yy440;
	}
yy475:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy481;
	default:	goto yy440;
	}
yy476:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy482;
	default:	goto yy440;
	}
yy477:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy483;
	default:	goto yy440;
	}
yy478:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy484;
	default:	goto yy440;
	}
yy479:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy485;
	default:	goto yy440;
	}
yy480:
	yych = *++s;
	switch (yych) {
	case 'y':	goto yy486;
	default:	goto yy440;
	}
yy481:
	yych = *++s;
	switch (yych) {
	case 'm':	goto yy487;
	default:	goto yy440;
	}
yy482:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy488;
	default:	goto yy440;
	}
yy483:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy489;
	default:	goto yy440;
	}
yy484:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy490;
	default:	goto yy440;
	}
yy485:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy491;
	default:	goto yy440;
	}
yy486:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt5 = s;
		goto yy493;
	case '=':
		yyt5 = s;
		goto yy495;
	default:	goto yy440;
	}
yy487:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy497;
	default:	goto yy440;
	}
yy488:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy498;
	default:	goto yy440;
	}
yy489:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy499;
	default:	goto yy440;
	}
yy490:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy486;
	default:	goto yy440;
	}
yy491:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy491;
	case ')':	goto yy500;
	default:	goto yy440;
	}
yy493:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy493;
	case '=':	goto yy495;
	default:	goto yy440;
	}
yy495:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy495;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt6 = s;
		goto yy502;
	default:	goto yy440;
	}
yy497:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy504;
	default:	goto yy440;
	}
yy498:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy505;
	default:	goto yy440;
	}
yy499:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy506;
	default:	goto yy440;
	}
yy500:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy500;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = s;
		goto yy507;
	default:	goto yy440;
	}
yy502:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt7 = s;
		goto yy509;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy502;
	case ';':
		yyt7 = s;
		goto yy511;
	default:	goto yy440;
	}
yy504:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy486;
	default:	goto yy440;
	}
yy505:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy486;
	default:	goto yy440;
	}
yy506:
	yych = *++s;
	switch (yych) {
	case 'g':	goto yy486;
	default:	goto yy440;
	}
yy507:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt2 = s;
		goto yy513;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy507;
	case ':':
		yyt2 = s;
		goto yy515;
	default:	goto yy440;
	}
yy509:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy509;
	case ';':	goto yy511;
	default:	goto yy440;
	}
yy511:
	++s;
	a = yyt1;
	b = yyt8;
	c = yyt2;
	d = yyt3;
	e = yyt4;
	f = yyt5;
	g = yyt6;
	h = yyt7;
	{
            callbacks->property(
                context,
                copy_string(buffers[0], c, d), // name
                copy_string(buffers[1], e, f), // type
                copy_string(buffers[2], a, b), // mode
                copy_string(buffers[3], g, h),
                NULL
            );
            continue;
        }
yy513:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy513;
	case ':':	goto yy515;
	default:	goto yy440;
	}
yy515:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy515;
	case 'a':
		yyt3 = s;
		goto yy517;
	case 'n':
		yyt3 = s;
		goto yy518;
	case 'o':
		yyt3 = s;
		goto yy519;
	case 's':
		yyt3 = s;
		goto yy520;
	case 'v':
		yyt3 = s;
		goto yy521;
	default:	goto yy440;
	}
yy517:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy522;
	default:	goto yy440;
	}
yy518:
	yych = *++s;
	switch (yych) {
	case 'u':	goto yy523;
	default:	goto yy440;
	}
yy519:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy524;
	default:	goto yy440;
	}
yy520:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy525;
	default:	goto yy440;
	}
yy521:
	yych = *++s;
	switch (yych) {
	case 'o':	goto yy526;
	default:	goto yy440;
	}
yy522:
	yych = *++s;
	switch (yych) {
	case 'y':	goto yy527;
	default:	goto yy440;
	}
yy523:
	yych = *++s;
	switch (yych) {
	case 'm':	goto yy528;
	default:	goto yy440;
	}
yy524:
	yych = *++s;
	switch (yych) {
	case 'j':	goto yy529;
	default:	goto yy440;
	}
yy525:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy530;
	default:	goto yy440;
	}
yy526:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy531;
	default:	goto yy440;
	}
yy527:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt4 = s;
		goto yy532;
	case '=':
		yyt4 = s;
		goto yy534;
	default:	goto yy440;
	}
yy528:
	yych = *++s;
	switch (yych) {
	case 'b':	goto yy536;
	default:	goto yy440;
	}
yy529:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy537;
	default:	goto yy440;
	}
yy530:
	yych = *++s;
	switch (yych) {
	case 'i':	goto yy538;
	default:	goto yy440;
	}
yy531:
	yych = *++s;
	switch (yych) {
	case 'd':	goto yy527;
	default:	goto yy440;
	}
yy532:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy532;
	case '=':	goto yy534;
	default:	goto yy440;
	}
yy534:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy534;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt5 = s;
		goto yy539;
	default:	goto yy440;
	}
yy536:
	yych = *++s;
	switch (yych) {
	case 'e':	goto yy541;
	default:	goto yy440;
	}
yy537:
	yych = *++s;
	switch (yych) {
	case 'c':	goto yy542;
	default:	goto yy440;
	}
yy538:
	yych = *++s;
	switch (yych) {
	case 'n':	goto yy543;
	default:	goto yy440;
	}
yy539:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
		yyt6 = s;
		goto yy544;
	case ',':
		yyt6 = s;
		goto yy546;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy539;
	default:	goto yy440;
	}
yy541:
	yych = *++s;
	switch (yych) {
	case 'r':	goto yy527;
	default:	goto yy440;
	}
yy542:
	yych = *++s;
	switch (yych) {
	case 't':	goto yy527;
	default:	goto yy440;
	}
yy543:
	yych = *++s;
	switch (yych) {
	case 'g':	goto yy527;
	default:	goto yy440;
	}
yy544:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy544;
	case ',':	goto yy546;
	default:	goto yy440;
	}
yy546:
	yych = *++s;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy546;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt7 = s;
		goto yy548;
	default:	goto yy440;
	}
yy548:
	yych = *++s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy548;
	case ';':
		yyt8 = s;
		goto yy550;
	default:	goto yy440;
	}
yy550:
	++s;
	a = yyt1;
	b = yyt2;
	c = yyt3;
	d = yyt4;
	e = yyt5;
	f = yyt6;
	g = yyt7;
	ws = yyt8;
	h = s - 1;
	{
            callbacks->property(
                context,
                copy_string(buffers[0], a, b),  // name
                copy_string(buffers[1], c, d), // type
                "read,write", // mode
                copy_string(buffers[2], e, f), // symbol1
                copy_string(buffers[3], g, h) // symbol2
            );
            continue;
        }
}

    }
}
